orbitjs/orbit

lib/orbit-common/source.js, test/tests/orbit_common/unit/source-test.js
Debugging tools will need to know about created sources!
=> Add OC.Source.Created hook for debugging tools

test/tests/orbit_common/unit/memory-source-test.js
I'm not sure this is the right way to solve it.  Some comments inline in the code.
=> cache: fix transform that throw errors from breaking sources

lib/orbit-common/cache.js, lib/orbit/operation.js, test/test-support/test-loader.js, test/tests/orbit-common/unit/cache-test.js, test/tests/orbit/unit/lib/operations-test.js
Filters out:
* Link operations against records that haven't been added yet
* Add link operations that make no change
* Remove link operations that make no change
=> Don't apply redundent operations to the cache

lib/orbit-common/cache.js, test/tests/integration/memory-source-sync-with-blocking-connector-test.js
Fixes infinite argument loop problem when two sources are connected with sync blocking transform connectors
=> Perform related inverse operations after parent operation

lib/orbit-common/lib/exceptions.js, lib/orbit/lib/exceptions.js
I'm really tired of "Unhandled rejection error: [object object]" in my promises :)
=> Better Exceptions

lib/orbit-common/cache.js, lib/orbit-common/jsonapi-source.js, lib/orbit-common/memory-source.js, lib/orbit-common/schema.js, lib/orbit-common/source.js
As discussed in #142 - I had the time today @opsb @dgeb :smile:
=> Rename to linkDefinition and modelDefinition

lib/orbit-common/jsonapi-serializer.js, test/tests/orbit-common/unit/jsonapi-serializer-test.js
Finally adds serializer unit tests, rather than just testing the serializer in integration tests.
Fixes a few issues with serialization / deserialization that were uncovered.
=> Test and fix JSONAPISerializer.

lib/orbit/lib/objects.js
Resolves #176 
===
@dgeb, we may **also** want to use `@for`? I replaced it in this PR, but lemme know if you want me to keep it as well.
=> Namespace Class under Orbit.

.travis.yml, README.md
Instead of the automated #185 which missed the header where the travis build icon is.
=> Added Gitter badge

lib/orbit/transaction.js, test/tests/integration/transaction-test.js
Support use cases that require tracking more than inverse operations.
=> Track operations on a transaction.

test/tests/integration/three-memory-source-blocking-connector-test.js, test/tests/integration/three-memory-source-sync-with-blocking-connector-test.js
This is the last of the memory source tests
=> Update three memory source integration tests

lib/orbit-common.js, lib/orbit-common/lib/operations.js, lib/orbit-common/operation-processors/cache-integrity-processor.js, lib/orbit-common/operation-processors/schema-consistency-processor.js, lib/orbit-common/schema.js, lib/orbit-common/store.js, test/tests/integration/memory-source-sync-with-blocking-connector-test.js, test/tests/orbit-common/unit/cache-test.js, test/tests/orbit-common/unit/jsonapi-source-test.js, test/tests/orbit-common/unit/lib/operations-test.js, test/tests/orbit-common/unit/operation-processors/cache-integrity-processor-test.js, test/tests/orbit-common/unit/operation-processors/schema-consistency-processor-test.js, test/tests/orbit-common/unit/store-test.js, test/tests/orbit-common/unit/transaction-test.js
Resolves https://github.com/orbitjs/orbit.js/issues/220
=> Allow operations to be identified without referring to schema

lib/orbit-common/oql/evaluator.js, lib/orbit-common/oql/expressions.js, lib/orbit-common/oql/operators.js, lib/orbit/lib/exceptions.js
This is caused by a bug in jshint, will be fixed in 2.9.1
=> Switch to var to avoid jshint warnings

lib/orbit-common/schema.js, test/tests/integration/memory-source-sync-with-blocking-connector-test.js, test/tests/orbit-common/unit/jsonapi-serializer-test.js, test/tests/orbit-common/unit/jsonapi-source-test.js, test/tests/orbit-common/unit/schema-test.js, test/tests/orbit-common/unit/store-test.js
Update `schema.normalize` to ensure relationships are defined
```
hasOnes => null
hasManys => {};
```
=> Ensure relationships are initialized

lib/orbit-common/cache/query-operators.js, test/tests/orbit-common/unit/cache-test.js
Based on work by @opsb in https://github.com/orbitjs/orbit.js/pull/254
=> Introduce Cache query ops: record & recordsOfType.

lib/orbit-common/cache/inverse-transforms.js, lib/orbit-common/query/builder.js, lib/orbit-common/query/operators.js, lib/orbit-common/query/terms.js, lib/orbit-common/store.js, lib/orbit-common/transform-tracker.js, lib/orbit/lib/promises.js, test/tests/integration/jsonapi-test.js, test/tests/orbit-common/unit/jsonapi-source-test.js, test/tests/orbit-common/unit/store-test.js, test/tests/support/matchers.js, test/tests/support/schemas.js
Note that the head is wip but the previous commit `dfa478c` is green
=> Blocking store

lib/orbit-common/lib/operations.js, test/tests/orbit-common/unit/lib/operations-test.js
Now works with record-aware ops.
=> Refactor coalesceOperations.

src/orbit-common/jsonapi-source.js, test/tests/orbit-common/unit/jsonapi-source-test.js
If a single transform or fetch operation requires more than one ajax
request, requests will be performed sequentially and resolved
together.
From the perspective of Orbit, these operations will all succeed or
fail together.
The new `maxRequestsPerTransform` and `maxRequestsPerFetch` options 
allow limits to be set on this behavior. These options should be set
to `1` if your client/server configuration is unable to resolve
partially successful transforms.
=> JSONAPISource: Allow multiple requests per transform or fetch.

src/orbit-common/jsonapi/fetch-requests.js, test/tests/orbit-common/unit/jsonapi-source-test.js
=> Add relatedRecords to jsonapi fetch-requests

.gitignore, .travis.yml, Brocfile.js, bower.json, package.json
Remove bower dependency and upgrade loader.js, jquery, rsvp, and qunitjs packages.
=> Remove bower dependencies.

src/orbit/action.js
It appears that the `Evented` methods weren't used outside of the `Action` class. If these methods don't need to be part of the public interface, then we can remove some indirection from the implementation and narrow the interface.
=> Remove Evented from action

src/orbit/action-queue.js, test/tests/orbit/unit/action-queue-test.js
Refactor ActionQueue's internal action properties:
* `content` -> `actions`
* `current` -> `currentAction`
And introduce `beforeAction` event.
=> ActionQueue refactor

src/orbit-common/jsonapi-source.js, test/tests/integration/coordinator-test.js, test/tests/support/jsonapi.js
Ensure that response data is read properly from response object when
fetch errors are encountered.
=> Fix fetch error handling.

src/orbit/action-queue.js, test/tests/orbit/unit/action-queue-test.js
ActionQueue#process now resolves regardless of whether errors have
occurred during processing. This prevents a number of uncaught 
rejections when the queue is auto-processing (its default mode).
New properties `error` and `complete` allow clients to ascertain the
state of the queue at any time, and are especially useful when 
processing has stopped.
Also, events are no longer used for internally communicating when
processing should be resolved.
=> Tweak ActionQueue processing.

src/interfaces/queryable.js, src/query.js, test/tests/unit/query-test.js
=> Add support for query options

packages/@orbit/core/src/log.ts, packages/@orbit/core/test/log-test.ts
Parallels the TaskQueue change event.
=> Emit `change` event any time log contents change.

packages/@orbit/coordinator/.npmignore, packages/@orbit/coordinator/Brocfile.js, packages/@orbit/coordinator/LICENSE, packages/@orbit/coordinator/README.md, packages/@orbit/coordinator/package.json, packages/@orbit/coordinator/src/coordinator.ts, packages/@orbit/coordinator/src/index.ts, packages/@orbit/coordinator/src/strategies/log-truncation-strategy.ts, packages/@orbit/coordinator/src/strategy.ts, packages/@orbit/coordinator/test/coordinator-test.ts, packages/@orbit/coordinator/test/strategies/log-truncation-strategy-test.ts, packages/@orbit/coordinator/test/strategy-test.ts, packages/@orbit/coordinator/test/support/orbit-setup.ts, packages/@orbit/coordinator/test/support/rsvp.ts, packages/@orbit/coordinator/test/test-helper.ts, packages/@orbit/coordinator/testem.json, packages/@orbit/coordinator/tsconfig.json, packages/@orbit/coordinator/tsconfig.tests.json, packages/@orbit/data/src/index.ts
Also introduce a new concept: coordination strategies.
=> Extract @orbit/coordinator from @orbit/data

packages/@orbit/coordinator/src/coordinator.ts, packages/@orbit/coordinator/src/strategies/log-truncation-strategy.ts, packages/@orbit/coordinator/test/coordinator-test.ts, packages/@orbit/coordinator/test/strategies/log-truncation-strategy-test.ts
Simplify LogTruncationStrategy implementation.
Also, activate/deactivate strategies serially and in order.
=> Coordinator tweaks

packages/@orbit/store/src/cache/query-operators.ts, packages/@orbit/store/test/cache-test.ts
Allow `offset` and `limit` options.
=> Support `page` query expression in @orbit/store

packages/@orbit/utils/src/objects.ts, packages/@orbit/utils/src/uuid.ts, packages/@orbit/utils/tsconfig.json, packages/@orbit/utils/tsconfig.tests.json
First step.. I left a lot of `any`s on the generic code. We can try to refine them if we find value in it later.
=> Strictly type @orbit/utils

package-lock.json, package.json, packages/@orbit/jsonapi/src/lib/request-settings.ts
Replace `for…of` with `forEach`.
Fixes #449
=> Eliminate use of for…of

packages/@orbit/data/src/source.ts
=> Fix missing import

packages/@orbit/core/src/task-queue.ts
`_settle` is now used by `push`, `retry`, `skip` and `clear` to settle task processing and return the appropriate promise.
=> Centralize TaskQueue settling logic

packages/@orbit/core/src/task-queue.ts, packages/@orbit/core/test/task-queue-test.ts
Events that participate in task processing, including `complete`, `fail`, `beforeTask` and `task`, should be settled in series before processing proceeds.
This enables listeners to delay any point in processing. We can thereby guarantee that listeners have been engaged before `process()` resolves.
=> Settle all TaskQueue events while processing

packages/@orbit/coordinator/src/strategies/log-truncation-strategy.ts, packages/@orbit/coordinator/test/strategies/log-truncation-strategy-test.ts
Instead of performing the LogTruncationStrategy on every `transform` event, observe the `complete` event for each source’s `requestQueue` and `syncQueue`.
Only perform log truncation when all queues are empty.
This prevents premature log truncation which might result in errors such as the same transform being applied twice to a source.
=> Perform LogTruncationStrategy when queues are emptied

packages/@orbit/jsonapi/src/jsonapi-source.ts
=> Bind default fetch to “globals” scope

packages/@orbit/jsonapi/src/jsonapi-document.ts
Related issue: #561
CC @simonihmig
=> Let ResourceIdentity be null, fixes #561

packages/@orbit/coordinator/package-lock.json, packages/@orbit/coordinator/package.json, packages/@orbit/core/package-lock.json, packages/@orbit/core/package.json, packages/@orbit/data/package-lock.json, packages/@orbit/data/package.json, packages/@orbit/immutable/package-lock.json, packages/@orbit/immutable/package.json, packages/@orbit/indexeddb-bucket/package-lock.json, packages/@orbit/indexeddb-bucket/package.json, packages/@orbit/indexeddb/package-lock.json, packages/@orbit/indexeddb/package.json, packages/@orbit/jsonapi/package-lock.json, packages/@orbit/jsonapi/package.json, packages/@orbit/local-storage-bucket/package-lock.json, packages/@orbit/local-storage-bucket/package.json, packages/@orbit/local-storage/package-lock.json, packages/@orbit/local-storage/package.json, packages/@orbit/record-cache/package.json, packages/@orbit/store/package-lock.json, packages/@orbit/store/package.json, packages/@orbit/utils/package-lock.json, packages/@orbit/utils/package.json
devDeps `merge` and `randomatic` need to be bumped due to vulnerabilities:
* https://nvd.nist.gov/vuln/detail/CVE-2018-16469
* https://nvd.nist.gov/vuln/detail/CVE-2017-16028
=> Fix security alerts

packages/@orbit/jsonapi/src/jsonapi-source.ts, packages/@orbit/jsonapi/test/jsonapi-source-test.ts
The `allowedContentTypes` setting makes it even easier to control which response content types are recognized as valid by the source.
=> [jsonapi] allowedContentTypes can be customized

packages/@orbit/serializers/.npmignore, packages/@orbit/serializers/Brocfile.js, packages/@orbit/serializers/LICENSE, packages/@orbit/serializers/README.md, packages/@orbit/serializers/package-lock.json, packages/@orbit/serializers/package.json, packages/@orbit/serializers/src/boolean-serializer.ts, packages/@orbit/serializers/src/date-serializer.ts, packages/@orbit/serializers/src/date-time-serializer.ts, packages/@orbit/serializers/src/index.ts, packages/@orbit/serializers/src/number-serializer.ts, packages/@orbit/serializers/src/serializer.ts, packages/@orbit/serializers/src/string-serializer.ts, packages/@orbit/serializers/test/boolean-serializer-test.ts, packages/@orbit/serializers/test/date-serializer-test.ts, packages/@orbit/serializers/test/date-time-serializer-test.ts, packages/@orbit/serializers/test/number-serializer-test.ts, packages/@orbit/serializers/test/string-serializer-test.ts, packages/@orbit/serializers/testem.json, packages/@orbit/serializers/tsconfig.json, packages/@orbit/serializers/tsconfig.tests.json
Introduce a set of interfaces and serializer classes that can be used by sources to serialize / deserialize primitive types.
=> Introduce @orbit/serializers

README.md
This is an attempt to address the confusion mentioned in #583, and better motivate developers to try out Orbit.
Most details, including an enumeration of packages, will be left to the docs.
=> Clarify Orbit’s purpose and primary use cases

packages/@orbit/store/src/store.ts, packages/@orbit/store/test/store-test.ts
As discussed on gitter, this will add the rebase method programmed by @dgeb + some tests and a minor modification to make the tests run through from me.
```bash
npm install Bernhard---H/npm-registry.git#orbit-store-v0.16.0-beta.1-rebase.1-gitpkg
```
=> Add Store.rebase()

packages/@orbit/indexeddb/test/source-test.ts, packages/@orbit/local-storage/test/source-test.ts
=> Add tests to verify local storage + indexeddb sources are not reset on initialization

packages/@orbit/indexeddb/src/cache.ts
=> Rationalize indexes

packages/@orbit/jsonapi/src/jsonapi-serializer.ts, packages/@orbit/jsonapi/src/resource-document.ts, packages/@orbit/jsonapi/test/jsonapi-serializer-operations-test.ts
=> @orbit/jsonapi-serializer operations (deserialize)

packages/@orbit/data/src/schema.ts
- Also fixes a nearby spelling errors in docs
=> Warn if naive singularize method receives a word that doesn't end in "s"

packages/@orbit/indexeddb/src/cache.ts, packages/@orbit/local-storage/src/cache.ts, packages/@orbit/memory/src/memory-cache.ts, packages/@orbit/record-cache/src/async-record-cache.ts, packages/@orbit/record-cache/src/operation-processors/async-cache-integrity-processor.ts, packages/@orbit/record-cache/src/operation-processors/async-schema-consistency-processor.ts, packages/@orbit/record-cache/src/operation-processors/sync-cache-integrity-processor.ts, packages/@orbit/record-cache/src/operation-processors/sync-schema-consistency-processor.ts, packages/@orbit/record-cache/src/operation-processors/utils/cache-integrity-utils.ts, packages/@orbit/record-cache/src/operation-processors/utils/schema-consistency-utils.ts, packages/@orbit/record-cache/src/operators/async-inverse-patch-operators.ts, packages/@orbit/record-cache/src/operators/async-patch-operators.ts, packages/@orbit/record-cache/src/operators/async-query-operators.ts, packages/@orbit/record-cache/src/operators/sync-inverse-patch-operators.ts, packages/@orbit/record-cache/src/operators/sync-patch-operators.ts, packages/@orbit/record-cache/src/operators/sync-query-operators.ts, packages/@orbit/record-cache/src/record-accessor.ts, packages/@orbit/record-cache/src/sync-record-cache.ts, packages/@orbit/record-cache/test/async-record-cache-test.ts, packages/@orbit/record-cache/test/operation-processors/schema-consistency-processor-test.ts, packages/@orbit/record-cache/test/sync-record-cache-test.ts, packages/@orbit/record-cache/tsconfig.json
=> Refactor @orbit/record-cache with a stricter TS config

packages/@orbit/coordinator/src/strategies/log-truncation-strategy.ts, packages/@orbit/coordinator/src/strategy.ts, packages/@orbit/coordinator/test/strategy-test.ts, packages/@orbit/data/src/source-interfaces/pullable.ts, packages/@orbit/data/src/source-interfaces/pushable.ts, packages/@orbit/data/src/source-interfaces/queryable.ts, packages/@orbit/data/src/source-interfaces/syncable.ts, packages/@orbit/data/src/source-interfaces/updatable.ts, packages/@orbit/data/src/source.ts, packages/@orbit/data/test/source-test.ts, packages/@orbit/integration-tests/test/memory-bucket-test.ts
=> Introduce explicit source activation + deactivation

packages/@orbit/indexeddb/src/source.ts, packages/@orbit/memory/src/memory-cache.ts
=> Add more deprecations

packages/@orbit/data/src/source-interfaces/pullable.ts, packages/@orbit/data/src/source-interfaces/pushable.ts, packages/@orbit/data/src/source-interfaces/queryable.ts, packages/@orbit/data/src/source-interfaces/syncable.ts, packages/@orbit/data/src/source-interfaces/updatable.ts
Improves code clarity. Behavior remains unchanged.
=> Convert source interface implementations to use async/await

packages/@orbit/jsonapi/src/jsonapi-serializer.ts, packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
=> fix(jsonapi): don't deserialize null attributes

packages/@orbit/coordinator/src/strategies/request-strategy.ts, packages/@orbit/coordinator/test/strategies/request-strategy-test.ts
Custom handler functions on a RequestStrategy, such as `action`, `blocking`, and `filter`, should receive all args emitted from the source event:
* For `beforeX` events such as `beforeQuery`, the handler functions will receive the second `hints` argument.
* For `x` events such as `query`, the handler functions will receive the second `result` argument.
* For `xFail` events such as `queryFail`, the handler functions will receive the second `error` argument.
This allows for fuller fidelity custom handlers.
=> Ensure that RequestStrategy handler functions receive all args

packages/@orbit/core/src/bucket.ts, packages/@orbit/core/src/evented.ts, packages/@orbit/core/src/log.ts, packages/@orbit/core/src/notifier.ts, packages/@orbit/core/src/task-queue.ts, packages/@orbit/core/test/evented-test.ts, packages/@orbit/data/src/schema.ts, packages/@orbit/data/src/source.ts, packages/@orbit/record-cache/src/async-record-cache.ts, packages/@orbit/record-cache/src/sync-record-cache.ts
This is a developer UX improvement inspired by https://github.com/ai/nanoevents
It makes it easier to write clean up code.
What do you think @dgeb?
=> Return off function from evented subscribers

packages/@orbit/record-cache/src/operators/async-query-operators.ts, packages/@orbit/record-cache/src/operators/sync-query-operators.ts, packages/@orbit/record-cache/test/async-record-cache-test.ts, packages/@orbit/record-cache/test/sync-record-cache-test.ts
- Added null case for relatedRecord filter (sync/Async)
- Added tests (sync/Async)
Closes issue #700
=> fix: added null case to relatedRecord filter processing

packages/@orbit/jsonapi/src/jsonapi-serializer.ts, packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
=> [BUGFIX] Always allow serialization of null attributes

packages/@orbit/data/src/operation.ts, packages/@orbit/data/test/operation-test.ts, packages/@orbit/jsonapi/src/jsonapi-serializer.ts, packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
Backports #710 and #712 to v0.16 release branch
=> Backport fixes to v0.16

packages/@orbit/record-cache/src/async-record-cache.ts, packages/@orbit/record-cache/src/live-query/live-query.ts, packages/@orbit/record-cache/src/sync-record-cache.ts, packages/@orbit/record-cache/test/async-record-cache-test.ts, packages/@orbit/record-cache/test/sync-record-cache-test.ts
This makes it easier to work with pull based reactive systems
=> Add debounce option to liveQuery

packages/@orbit/integration-tests/.browserslistrc, packages/@orbit/integration-tests/.eslintignore, packages/@orbit/integration-tests/.eslintrc.js, packages/@orbit/integration-tests/.npmignore, packages/@orbit/integration-tests/.prettierrc.js, packages/@orbit/integration-tests/LICENSE, packages/@orbit/integration-tests/README.md, packages/@orbit/integration-tests/package.json, packages/@orbit/integration-tests/test/index.html, packages/@orbit/integration-tests/test/memory-bucket-test.ts, packages/@orbit/integration-tests/test/store-jsonapi-clientid-pessimistic-test.ts, packages/@orbit/integration-tests/test/store-jsonapi-remoteid-optimistic-test.ts, packages/@orbit/integration-tests/test/store-jsonapi-remoteid-pessimistic-test.ts, packages/@orbit/integration-tests/test/support/jsonapi.ts, packages/@orbit/integration-tests/testem.js, packages/@orbit/integration-tests/tsconfig.json, packages/@orbit/integration-tests/tsconfig.tests.json
This private package was accidentally dropped during the build refactor.
=> Reintroduce @orbit/integration-tests

packages/@orbit/core/src/evented.ts, packages/@orbit/core/src/notifier.ts, packages/@orbit/data/src/schema.ts, packages/@orbit/data/src/source.ts, packages/@orbit/data/src/transform-builder.ts, packages/@orbit/indexeddb/src/indexeddb-source.ts, packages/@orbit/jsonapi/src/jsonapi-request-processor.ts, packages/@orbit/jsonapi/src/jsonapi-serializer.ts, packages/@orbit/jsonapi/src/jsonapi-source.ts, packages/@orbit/jsonapi/src/lib/jsonapi-request-options.ts, packages/@orbit/jsonapi/src/lib/transform-requests.ts, packages/@orbit/jsonapi/test/jsonapi-source-test.ts, packages/@orbit/memory/src/memory-cache.ts, packages/@orbit/record-cache/src/async-record-cache.ts, packages/@orbit/record-cache/src/sync-record-cache.ts, packages/@orbit/utils/src/objects.ts, packages/@orbit/utils/test/object-test.js
Removes behavior deprecated by v0.16.0 or earlier.
=> Remove v0.16 deprecations

packages/@orbit/indexeddb/src/indexeddb-cache.ts, packages/@orbit/indexeddb/test/indexeddb-source-test.ts
Fixes a test of indexeddb upgrades that's been skipped for a while.
=> Finish opening/upgrading indexeddb dbs before closing them

packages/@orbit/build/package.json, yarn.lock
This reverts commit d17a02c7d9069ddb425c1218459a5bea9fe14f6d.
=> Revert "Update snowpack"

packages/@orbit/data/src/operation.ts, packages/@orbit/data/test/operation-test.ts
Expands `recordDiffs` to handle all possible record fields. The behavior remains the same if only `attributes` and `keys` have changed - an array of `replaceAttribute` / `replaceKey` ops will be returned. Any other diffs will result in a single `updateRecord` op returned.
=> Fill out recordDiffs implementation

packages/@orbit/data/src/operation.ts, packages/@orbit/data/test/operation-test.ts
This should be backported to `release-0-16`
Fixes #777
=> Support coalescing of addRecord/updateRecord + updateRecord

packages/@orbit/data/src/operation.ts, packages/@orbit/data/test/operation-test.ts
Support coalescing of addRecord/updateRecord + updateRecord
Fixes #777
=> Backport PR 780 to v0.16

packages/@orbit/memory/src/memory-source.ts
RecordCache#patch has been deprecated.
=> MemorySource: Use cache.update instead of cache.patch

packages/@orbit/validators/src/object-validator.ts, packages/@orbit/validators/test/object-validator-test.ts
=> validateObject should not accept null as a valid object

website/docs/modeling-data.md
Refs https://github.com/orbitjs/orbit/issues/914
=> Make clearer that relationships may have multiple possible target types.

website/package.json, website/src/pages/index.js, website/src/pages/index.module.scss, website/yarn.lock
Upgrade docusaurus and other website dependencies.
=> Upgrade docusaurus to 2.0.1
