orbitjs/orbit

- README.md
The `idField` configuration value was removed in version 0.5.0 [1].
Update the project's README.md file with the currently-supported method
for specifying primary keys.
[1] See commit 55900d4f671a4c778eb0b8c4b629ebe3aa10e2d6
> Update example code to use current API

- lib/orbit/operation.js
- test/tests/orbit/unit/operation-test.js
Because I'm roundtripping operations via firebase I need to serialize and then deserialize them. This PR allows all operation attributes to be specified in the constructor e.g. 
new Operation(id: 'id', path: 'planet/1', value: {}, log: log).
> Allow all operation attributes to be specified for new Operation(options)

- lib/orbit-common/source.js
I noticed some operations flying around without any ids and noticed these points where operations are created without using the new Operation class (I'm presuming your intention is to always use the Operation class).
> Wrap operations in Operation class

- lib/orbit-common/jsonapi-source.js
- lib/orbit-common/memory-source.js
- lib/orbit/operation.js
- lib/orbit/transform-connector.js
- lib/orbit/transformation.js
- test/tests/integration/rest-memory-local-non-blocking-transforms-test.js
- test/tests/integration/rest-memory-source-assist-test.js
- test/tests/orbit/unit/operation-test.js
This solves a number of issues related to transformations, relationships, and timeouts.
This introduces a new methodology for tracking operation relationships. Operations are now considered "related" if they share a common ancestor. Related operations are always processed together as part of the same transformation.
This change is validated by the tests:
* formerly, some flip-flopping of values was happening in non-blocking tests, since related transforms weren't always processed together.
* new "assistFind" tests validate the solution to #109.
Furthermore, the TransformConnector was diff'ing reverse links (`__rev`) along with objects. These are now explicitly ignored so that reverse link tracking can remain entirely a concern of each source that tracks them.
> Improve tracking of related operations

- test/tests/test-helper.js
Adds a test helper for creating ops.
e.g.
op("add", ["contact", "123abc", "name"], "Jim")
=>
{op: "add", path: ["contact", "123abc", "name"], value: "Jim"}
> Add `op` test helper

- lib/orbit/lib/objects.js
- test/tests/orbit/unit/lib/object-test.js
Adds orbit/lib/objects#merge helper for merging objects
e.g.
test("`merge` combines two objects", function() {
var a = { firstNames: 'Bob'},
b = { lastName: 'Dobbs', 'title': 'Mr.'},
expected = { title: 'Mr.', firstNames: 'Bob', lastName: 'Dobbs'};
deepEqual(merge(a, b), expected, 'Object values are not merged');
deepEqual(a, { firstNames: 'Bob' }, 'Original object mutated');
});
> Add `merge` helper

- lib/orbit/lib/operations.js
- test/tests/orbit/unit/lib/operations-test.js
Adds orbit/lib/operation#coalesceOperations helper. It will coalesce a list of operations into the minimal set of operations that will produce the same transformations on a target document. 
@dgeb the main difference over the version you had in peeps-ember-orbit is that it combines attribute and link operations into record operations e.g.
test("can coalesce attributes into records", function(){
shouldCoalesceOperations(
[
op('add', ['contact', '1234'], { id: '1234' }),
op('add', ['contact', '1234', 'name'], "Jim")
],
[
op('add', ['contact', '1234'], { id: '1234', name: "Jim" })
]
);
});
There's one case where it's perhaps too aggressive, it will coalesce add link operations into the record, but before the target object has been created. I haven't seen any issues with this testing against …
> Add coalesceOperations helper

- .travis.yml
- package.json
- testem.json
Allows `testem` to just launch it's chrome and show tests in terminal.
> add testem commands for watch

- lib/orbit-common/cache.js
- test/tests/orbit-common/unit/cache-test.js
I also added some console logging in the "marked for removal" logic (as it's own commit, in case you don't want to keep it around)
> Fix call stack overflow when removing circular hasOne inverse

- lib/orbit-common/cache.js
- lib/orbit-common/schema.js
- lib/orbit/transform-connector.js
- test/tests/orbit-common/unit/cache-test.js
Polluting each record with `__rev` data leads to that data leaking
into `didTransform` events inappropriately. This data should be
maintained separately per-cache instead.
This also simplifies `Cache#transform`, which no longer needs special
logic for reverse link transforms.
> Isolate reverse link tracking.

- lib/orbit/lib/diffs.js
- test/tests/orbit/unit/lib/diffs-test.js
Currently diffing dates always returns undefined for diffs(dateA, dateB). This PR will generate the expected replace operation.
> Add support for diffing dates

- test/tests/orbit/unit/lib/diffs-test.js
Just a couple of test cases to ensure replacing dates doesn't regress.
> Add tests for replacing date => string and vica versa

- lib/orbit-common.js
- lib/orbit-common/lib/exceptions.js
- lib/orbit-common/schema.js
- test/tests/orbit-common/unit/schema-test.js
Added this because I was having quite a few "attempt to read keys of undefined" errors
cropping up from this function.  I'd rather throw an exception with a known error message.
cc @opsb maybe you want to reuse this `schemaFor` in #139 ?
> OC.ModelNotRegisteredException

- lib/orbit-common.js
- lib/orbit-common/cache.js
- lib/orbit-common/jsonapi-source.js
- lib/orbit-common/lib/exceptions.js
- lib/orbit-common/memory-source.js
- lib/orbit-common/schema.js
- lib/orbit-common/source.js
Added schema.linkPropertiesFor(type, link) which throws the following errors:
Type 'planet' not found for 'planet.moons'
Link 'moons' not found for 'planet.moons'
I've swapped out any calls of the form this.schema.models[type].links[link] to use this method instead.
> Better errors when link not found

- lib/orbit-common/schema.js
Allows ModelNotRegisteredException to be thrown if needed.
> Use Schema#schemaFor consistently.

- Brocfile.js
- build-support/globalize-orbit-common-jsonapi.js
- lib/orbit-common/jsonapi-patch-source.js
- lib/orbit-common/jsonapi-source.js
- test/tests/orbit-common/unit/jsonapi-patch-source-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
The jsonpatch extension warrants its own source, since it will typically
be used independently from the base JSONAPISource. This extraction
leads to a cleaner implementation of both sources.
----
_Coming soon_: Improved JSON API compliance for both sources.
> Extract JSONAPIPatchSource from JSONAPISource.

- lib/orbit-common/lib/exceptions.js
Spotted that the LinkNotRegisteredException wasn't actually being exported.
> Export missing exception

- lib/orbit-common/cache.js
- lib/orbit-common/lib/exceptions.js
- lib/orbit-common/operation-encoder.js
- lib/orbit-common/operation-processors/related-inverse-links.js
- lib/orbit-common/source.js
- test/tests/orbit-common/unit/memory-source-test.js
- test/tests/orbit-common/unit/operation-encoder-test.js
- test/tests/orbit-common/unit/operation-processors/related-inverse-links-test.js
- test/tests/test-helper.js
This PR pulls together operation encoding and identification into a single class, OperationEncoder. The intention is to ensure that operations are created and identified consistently. I've moved the terminology towards that of the schema but I think it could be made even closer (see below).
Currently this is handled by various conditions throughout the code such as operation.path.length === 4. This can cause problems however, e.g. I wanted to set a hasMany with
{op: `add`, path: `planet/planet1/__rel/moons`, value: {}}
but it was being misidentified as an add hasOne.
The operationEncoder introduces an `identify(operation)` method which will respond with one of the following: `addRecord`, `replaceRecord`, `removeRecord`, `addHasMany`, `replaceHasMany`, `removeHasMany`, `addToHasMany`, …
> Consolidate operation encoding and identification

- lib/orbit-common/cache.js
- lib/orbit-common/jsonapi-source.js
- lib/orbit-common/memory-source.js
- lib/orbit-common/source.js
- test/tests/integration/three-memory-source-blocking-connector-test.js
- test/tests/orbit-common/unit/cache-test.js
The `Cache#trackChanges` option has been removed.
Cache is longer evented and no longer emits `didTransform` events.
Transform notifications are now the responsibility of the cache's
owner (i.e. the caller of `Cache#transform`).
As a result, any ancillary changes to the cache (such as reverse
and inverse link maintenance) will not bubble out of the cache.
> Cache no longer tracks changes and emits events.

- lib/orbit-common/cache.js
- lib/orbit-common/operation-processors/related-inverse-links.js
This additional complexity is no longer necessary now that 
`didTransform` events are no longer being emitted from the Cache
when related inverse ops are applied.
> Remove concept of ignored / condemned paths from Cache#transform.

- Brocfile.js
- build-support/globalize-orbit-common-jsonapi.js
- lib/orbit-common/jsonapi-patch-source.js
- lib/orbit-common/jsonapi-serializer.js
- lib/orbit-common/jsonapi-source.js
- test/tests/integration/rest-memory-local-blocking-transforms-test.js
- test/tests/integration/rest-memory-local-non-blocking-transforms-test.js
- test/tests/integration/rest-memory-source-assist-test.js
- test/tests/orbit-common/unit/jsonapi-patch-source-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
This PR brings Orbit into compliance with v1.0 of the JSON API spec.
Most of this work is related to the `JSONAPISource` and `JSONAPISerializer`.
Also, the `JSONAPIPatchSource` has been temporarily removed now that the `jsonpatch` extension has been made an experimental part of the JSON API spec. Work can be expected to continue on both the extension and the source (although time will tell whether it remains part of the OrbitCommon lib).
Note that further work is planned related to JSON API, which will be discussed in separate issues.
> JSON API 1.0 compliance

- lib/orbit-common/cache.js
- lib/orbit/document.js
- test/tests/orbit/unit/document-test.js
This option allows the Document to skip throwing expensive exceptions when
a path can't be found.
> Introduce `quiet` option for Document `retrieve` and `test`.

- lib/orbit-common/cache.js
- lib/orbit-common/operation-processors/related-inverse-links.js
- lib/orbit-common/schema.js
- lib/orbit-common/source.js
Eliminate the need to instantiate multiple operation encoders
throughout an application, when a single object on the schema could
serve the same purpose.
> Define Schema#operationEncoder.

- README.md
- lib/orbit.js
Resolves #163 
===
@gnarf suggested adding a conditional for this – checking for `typeof Promise` – but when an environment doesn't support Promises this statement should not cause any harm. `Orbit.Promise` should simply *continue* to be `undefined`.
> Add default Promise.

- lib/orbit.js
Add a guard to using `Promise` - if `Promise` is not defined trying to assign it to something will cause a ReferenceError:
Fixes bug in #164
> Check for undefined before assigning Promise

- lib/orbit-common/memory-source.js
- test/tests/orbit-common/unit/memory-source-test.js
Currently, doing a `.find('planet', { secondaryKey: key })` will return `[]` and `[object]` even when it does find one.  This messes with the standard connections using when secondary keys for rescue/assist finds.
> Query by keys should reject missing, and always return an object

- lib/orbit-common/schema.js
- test/tests/orbit-common/unit/schema-test.js
Allows schemas to lazily define models, rather than requiring full
definitions upfront.
> Introduce Schema#modelNotDefined hook.

- lib/orbit-common/cache.js
- lib/orbit-common/jsonapi-source.js
- lib/orbit-common/memory-source.js
- lib/orbit-common/source.js
- test/tests/orbit-common/unit/cache-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/memory-source-test.js
This PR addresses a couple areas related to the `find` requestable method:
OC sources should now support `query` as a separate method from `find`. This simplifies the logic required to determine whether a request is a query or a request for a specific individual record or records. It also allows for separate requestable hooks for `find` vs. `query` (e.g. `rescueFind` vs `rescueQuery`).
Options, such as `include`, were not tested in these sources and the implementations need re-evaluation.
For now, these sources will throw exceptions if you pass `options` into `find`, `query`, `findLink`, or `findLinked`.
Of course, options can still be passed into custom sources.
The concept of a "sparse" cache is introduced to indicate that a cache is an incomplete representation of data. Most caches …
> Find / Query split

- lib/orbit/lib/operations.js
- test/tests/orbit/unit/lib/operations-test.js
This method now respects the order of the operations array and does not allow
reordering of operations that affect relationships.
> Fine tune `coalesceOperations`.

- .travis.yml
@dgeb this is enough to get travis running the tests again. The only remaining issue is that testem currently includes it's [own copy of qunit](https://github.com/testem/testem/blob/v0.9.11/public/testem/qunit.js). It's locked at 1.17 for now which means that none of the nested modules are run. There's a release candidate for 1.0 though which has qunit 1.20 configured so it might be worth waiting for that. Otherwise we can create a custom testem runner page.
> Use firefox v43 to run travis tests

- package.json
Temporary fix for https://github.com/orbitjs/orbit.js/issues/234
This includes the qunit upgrade that's in testem master. @dgeb seems fine for now, we can leave the issue open as a reminder to upgrade to the full release when it's available.
> Upgrade testem - includes qunit 1.20

- lib/orbit-common/cache.js
- lib/orbit-common/lib/operations.js
- test/tests/orbit-common/unit/cache/live-queries-test.js
@dgeb this ended up being a fairly superficial treatment. I've updated the external API, so `cache.liveQuery(operation => {})` now emits `addRecordToSet` or `removeRecordFromSet`. Internally though I'm still reusing the operations from the normalized schema and the operators are still emitting updates. The reason I'm still emitting updates is that operators further upstream in the RxJS chain need to know to recheck set membership for the updated record. Switching over to `addRecordToSet` and `removeRecordFromSet` should be fine but we'll need to choose a new operation to indicate updates (maybe `replaceRecordInSet`).
Anyway, this PR can be merged as is, the external API, `cache.liveQuery(operation => {})`, now emits the operations that we discussed.
> Introduce record set operations

- lib/orbit-common/jsonapi/update-requests.js
- lib/orbit-common/lib/identifiers.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/jsonapi/update-requests-test.js
- test/tests/orbit-common/unit/lib/identifiers-test.js
`getUpdateRequests` now consolidates requests as possible.
In order to make this more straightforward, `replaceRecord` is favored
in place of `replaceHasOne` and `replaceHasMany`.
> Consolidate JSON:API requests as possible.

- lib/orbit-common/cache.js
- lib/orbit-common/memory-source.js
- lib/orbit-common/query/builder.js
- lib/orbit-common/query/terms.js
- lib/orbit/lib/exceptions.js
- lib/orbit/query.js
- lib/orbit/query/builder.js
- lib/orbit/query/expression.js
- lib/orbit/query/terms.js
- lib/orbit/queryable.js
- lib/orbit/transform.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/memory-source-test.js
- test/tests/orbit-common/unit/query/builder-test.js
- test/tests/orbit/unit/query-test.js
- test/tests/orbit/unit/query/builder-test.js
- test/tests/orbit/unit/queryable-test.js
- test/tests/orbit/unit/transform-test.js
- test/tests/orbit/unit/transform/builder-test.js
Queries are used to extract data from a source.
The Query class mirrors the Transform class - it also assigns an `id` to each `query` and supports `Query.from` as well as the use of builders.
> Introduce Query class.

- lib/orbit-common/query/builder.js
- lib/orbit-common/query/operators.js
- lib/orbit-common/transform/builder.js
- lib/orbit-common/transform/operators.js
- lib/orbit/query/builder.js
- lib/orbit/query/operators.js
- lib/orbit/transform/builder.js
- test/tests/orbit-common/unit/cache-test.js
- test/tests/orbit-common/unit/cache/operation-processors/deletion-tracking-processor-test.js
- test/tests/orbit-common/unit/query/builder-test.js
- test/tests/orbit-common/unit/transform/builder-test.js
- test/tests/orbit/unit/transform/builder-test.js
TransformBuilder and QueryBuilder now define operators on an
`operators` property.
Furthermore, each operator should return `operators`, which allows
operations to be chained.
> Refactor builders to use operators property.

- lib/orbit-common/query/builder.js
- lib/orbit-common/query/operators.js
- test/tests/orbit-common/unit/query/builder-test.js
Provides cleaner and more flexible custom scopes and other usages of
custom terms from within operators.
> Allow QueryBuilder to register custom terms.

- lib/orbit-common/transaction.js
- test/tests/orbit-common/unit/transaction-test.js
New `autoCoalesce` option determines whether operations are coalesced
automatically on `commit()`.
New `coalesce` method performs coalescing of operations at any point.
Inverse operations are no longer tracked.
> Update Transaction with coalesce method and fixes.

- lib/orbit-common/cache/live-query-operators.js
- lib/orbit-common/cache/query-operators.js
- lib/orbit-common/jsonapi/fetch-requests.js
- lib/orbit-common/query/operators.js
- lib/orbit-common/query/terms.js
- test/tests/integration/jsonapi-test.js
- test/tests/orbit-common/unit/cache-test.js
- test/tests/orbit-common/unit/cache/live-queries-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/memory-source-test.js
- test/tests/orbit-common/unit/query/builder-test.js
- test/tests/orbit-common/unit/store-test.js
Instead of accepting `type, id` args, the query expressions `record`,
`relatedRecord` and `relatedRecords` accept a `recordIdentity` arg.
This is an object of the form `{ type, id }`.
[Closes #285]
> Query builder and expressions support record identity.

- src/orbit-common/jsonapi/transform-requests.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
Introduces a new test suite for JSONAPISource with no secondary keys in
the schema.
> JSONAPISource should not register key mappings for `id`.

- src/orbit-common/cache/query-operators.js
- src/orbit/lib/arrays.js
Babel's `for...of` relies on a polyfill for Symbol. Assuming `expressions` are just arrays, we can use other strategies. In particular, the need for an early return can be met with utility functions like `every` and `some`.
This removes our need for the Symbol polyfill and allows the tests for https://github.com/orbitjs/ember-orbit/pull/106 to pass.
> Eliminate uses of for...of

- src/orbit-common/cache/live-query-operators.js
- src/orbit-common/cache/query-operators.js
- src/orbit-common/jsonapi/fetch-requests.js
- src/orbit-common/query/builder.js
- test/tests/integration/coordinator-test.js
- test/tests/orbit-common/unit/cache-test.js
- test/tests/orbit-common/unit/cache/live-queries-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/query/builder-test.js
- test/tests/orbit-common/unit/store-test.js
- test/tests/orbit/unit/query-test.js
The less verbose form is more consistent with other query operators.
Furthermore, this name will allow a transition to supporting 
`records(...types)` instead of simply `records(type)`.
> Refactor `recordsOfType` => `records`.

- test/test-support/test-loader.js
After #312 we lost the ability to filter out linting tests in the QUnit test runner. This swaps out the JSHint specific code for something more general which will work with the ESLint tests.
> Let users skip lint tests in the QUnit runner

- src/orbit-common/cache.js
- src/orbit-common/jsonapi-source.js
- src/orbit-common/jsonapi/serializer.js
- test/tests/orbit-common/unit/jsonapi-serializer-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
* Set the JSONAPI Accept header by default.
* Refactor JSONAPISource#ajax to be more idiomatic.
* Fix serialization of relationship names to use translated resource names.
* Ensure that LiveQuery results observe `replaceRecord` operations (in addition to `addRecord` and `removeRecord`).
> Minor cleanup for JSONAPI source and serializer

- src/orbit-common/local-storage-source.js
- src/orbit-common/local-storage/fetch-operators.js
- src/orbit-common/local-storage/transform-operators.js
- test/tests/orbit-common/unit/local-storage-source-test.js
- test/tests/support/local-storage.js
- test/tests/test-helper.js
Removes Cache from LocalStorageSource, favoring direct access to local storage instead.
Also uses the approach taken in #135 (rebased) to store one record per local storage key, instead of storing data all in one key (which hits size/speed limits).
> Improve LocalStorageSource

- src/orbit-common/cache/operation-processors/cache-integrity-processor.js
- src/orbit-common/cache/operation-processors/schema-consistency-processor.js
- test/tests/orbit-common/unit/cache/operation-processors/cache-integrity-processor-test.js
- test/tests/orbit-common/unit/cache/operation-processors/deletion-tracking-processor-test.js
- test/tests/orbit-common/unit/cache/operation-processors/schema-consistency-processor-test.js
Refactor `CacheIntegrityProcessor` and `SchemaConsistencyProcessor` to handle the `replaceRecord` op and to optimize replacement of relationships in general.
[Fixes #325]
> Refactor cache operation processors to handle `replaceRecord` ops

- src/orbit-common/store.js
- test/tests/orbit-common/unit/store-test.js
Store calls `query` and then synchronously returns `cache.liveQuery`
without regard for the return value of `query()`.
> Implement Store#liveQuery.

- src/orbit-common/cache.js
- src/orbit-common/store.js
- test/tests/integration/coordinator-test.js
- test/tests/orbit-common/unit/cache-test.js
- test/tests/orbit-common/unit/cache/live-queries-test.js
- test/tests/orbit-common/unit/cache/observables/cache-observable-test.js
- test/tests/orbit-common/unit/cache/operation-processors/deletion-tracking-processor-test.js
- test/tests/orbit-common/unit/store-test.js
Refactors Cache#transform -> Cache#patch. The name `patch` is already
used to represent application of operations (vs. full Transforms), so
it’s consistent here.
Moves rollback capabilities to the Store class.
> Refactor Cache to handle operations, not transforms.

- src/orbit-common/cache/query-operators.js
- src/orbit-common/schema.js
- test/tests/orbit-common/unit/cache-test.js
- test/tests/orbit-common/unit/schema-test.js
To address https://github.com/orbitjs/ember-orbit/issues/116.
After looking through the flow of a `record` query from `ember-orbit` through `orbit` it seemed reasonable that querying for a type that did not exist with a `record` query would behave similarly to a `records` query.  After this change both a `record` and `records` query will allow lazy registration of the model type and throw `ModelNotRegisteredException` if no model can be registered. 
This change provides better error for the related issue by calling `modelNotDefined`, allowing Ember.Orbit to throw descriptive exceptions: https://github.com/orbitjs/ember-orbit/blob/03522ee0c77693d3f355003add28d752f3284692/addon/schema.js#L100.
Some small refactoring changes:
* `Schema#modelDefinition` retains its same behavior, but the …
> Ensure model type defined for record query

- src/orbit-common/source.js
- src/orbit/fetchable.js
- src/orbit/queryable.js
- src/orbit/source.js
- src/orbit/transformable.js
- src/orbit/updatable.js
- test/tests/orbit-common/unit/source-test.js
- test/tests/orbit/unit/fetchable-test.js
- test/tests/orbit/unit/queryable-test.js
- test/tests/orbit/unit/source-test.js
- test/tests/orbit/unit/transformable-test.js
- test/tests/orbit/unit/updatable-test.js
Orbit.Source provides a baseline for all sources and simplifies the
implementations of interfaces such as Transformable, Queryable, and
Fetchable. 
Every source has a `transformLog`, `transformed` method, and implements
`Evented`.
This allows for a distinction between sources that can emit transform
events but not have transforms applied. The latter is still covered by
the `Transformable` interface, which now simply adds the `transform`
method and is more inline with the other *able mixins.
----
_Sorry for the churn around the (Orbit/OC) Source classes. This change brings Orbit more inline with what @opsb and I settled on a while back, but still allows for the transform history tracking required by the recent refactor._
> Reintroduces Orbit.Source.

- src/orbit/updatable.js
- test/tests/orbit/unit/updatable-test.js
The return value of `update` is now consistent with `fetch` and 
`transform` - in all cases a promise is returned that resolves to the 
transforms applied to a source as a direct result of the method call.
Note that this will not include transforms applied as side effects from
event handlers, such as `beforeUpdate` or `update`.
> Updatable#update now returns transforms applied to source.

- src/orbit-common/jsonapi-source.js
- src/orbit-common/local-storage-source.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/local-storage-source-test.js
The Updatable interface allow these sources to participate in the 
“request” flow for updates (such that events are raised that other
sources can engage with). Under the hood, Updatable implicitly 
includes Transformable, and `update` calls `transform` internally, so 
the implementation doesn’t really change.
> JSONAPISource and LocalStorageSource implement Updatable.

- src/orbit-common/coordinator.js
- test/tests/integration/coordinator-test.js
Request flows include monitoring events and triggering methods related
to “requestable” interfaces like `Updatable`, `Queryable`, and
`Fetchable`.
Sync flows include monitoring the `transform` event and triggering the
`transform` method on a target `Transformable` source.
Request strategies can now include the `syncResults` option to have the
results of a request sync’d back to the source node (`syncResults` was
previously named `mergeTransforms`).
Also, the coordinator integration tests now include a sync strategy for
backing up to local storage.
> Improve separation of request / sync flows in the Coordinator.

- Brocfile.js
- package.json
The rxjs changelog from beta.8 to beta.10 claims no breaking changes.
This upgrade includes a workaround for Babel compiling issues, making
it possible to remove our own `withAsyncFix` workaround.
The rxjs-es package now includes symbol-observable 1.0.1 and I opted to
import `ponyfill.js` from that included dependency rather than
specifying it again in package.json.
@opsb, I don't know why we have to manually include the `symbol-observable` ponyfill file on our own, but I confirmed that build still breaks without this. As I recall this required some spelunking on your part that I'm not keen to repeat.
@opsb Could you give this a sanity check?
> Upgrade to rxjs 5.0.0-beta.10

- src/orbit/evented.js
- src/orbit/notifier.js
- test/tests/orbit/unit/evented-test.js
- test/tests/orbit/unit/notifier-test.js
- test/tests/orbit/unit/source-test.js
Method is no longer used by Orbit or Ember-Orbit.
> Remove `poll` method from Evented and Notifier.

- src/orbit-common/cache.js
- src/orbit-common/jsonapi-source.js
- src/orbit-common/local-storage-source.js
- src/orbit-common/schema.js
- src/orbit-common/store.js
- src/orbit/action-queue.js
- src/orbit/evented.js
- src/orbit/source.js
Moving mixin extensions out of constructors and instead applying them
to class prototypes provides a slight performance win and allows for 
method overrides in subclasses.
> Mixins should extend class prototypes.

- src/orbit-common/coordinator.js
- src/orbit-common/strategies/request-strategy.js
- src/orbit-common/strategies/sync-strategy.js
- test/tests/integration/coordinator-test.js
Create strategies separate from the Coordinator class:
* `RequestStrategy` - coordinates requests
* `SyncStrategy` - coordinates transforms
These strategies are now more robust than the implementations in
Coordinator. `activate` activates event listener(s) and `deactivate`
deactivates them.
> Introduce classes for coordination strategies.

- Brocfile.js
- README.md
- package.json
- src/orbit-common/jsonapi-source.js
- src/orbit-common/jsonapi/queries.js
- src/orbit-common/jsonapi/query-params.js
- src/orbit-common/jsonapi/transform-requests.js
- test/test-support/test-shims.js
- test/tests/integration/coordinator-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/orbit-common/unit/jsonapi/query-params-test.js
- test/tests/support/jsonapi.js
- test/tests/support/orbit-setup.js
- test/tests/test-helper.js
Using `fetch` provides the following benefits:
* More natural promise-driven API with improved error handling.
* Eliminates jQuery dependency.
* Enables usage of Orbit in non-browser environments.
* Simplifies testing of network requests, which can now be done with
simple stubbing.
Orbit now requires the use of a polyfill in environments without `fetch` 
support.
> Replace jQuery.ajax with fetch.

- README.md
- src/orbit-common/jsonapi-source.js
- src/orbit.js
- src/orbit/main.js
- test/tests/integration/coordinator-test.js
- test/tests/orbit-common/unit/jsonapi-source-test.js
- test/tests/support/orbit-setup.js
By using `Orbit.fetch` instead of requiring a global `fetch`, Orbit can
more flexibly allow this method to be polyfilled or ponyfilled. 
If global `fetch` is present, it will be used as the default value for 
`Orbit.fetch`. However, `Orbit.fetch` can alternatively be set 
directly, which will override other alternatives.
This makes `Orbit.fetch` consistent with `Orbit.Promise`.
/cc @mitchlloyd
> Allow `fetch` to be polyfilled or ponyfilled.

- src/orbit-common/coordinator.js
- src/orbit/action-queue.js
- src/orbit/action.js
- test/tests/orbit/unit/action-queue-test.js
- test/tests/orbit/unit/action-test.js
Refactor `Action#complete` -> `Action#settle()`. Settled is the appropriate term for a non-pending promise. Thus the `settle()` method returns a settled promise that has either been
resolved or rejected.
Introduce `Action.from` helper method, which coerces arg to an `Action`.
Introduce `clear`, `shift`, and `unshift` methods to `ActionQueue` to allow fine control of queue.
> Refactor Action and ActionQueue

- Brocfile.js
- package.json
Proof-of-concept:
```
$ broccoli build build
$ cd build/npm
$ npm link
$ npm link orbit.js
```
```javascript
// This should now be possible from within your node project
var Orbit = require('orbit.js');
var OC = require('orbit.js/orbit-common');
```
> Compile to CommonJS with support for npm

- src/orbit/evented.js
- test/tests/orbit/unit/evented-test.js
* remove `resolve` method - not used and poorly named
* refactor `settle` and `series` methods
* drop support for subscribing to / emitting multiple events in one call
Closes #216
> Reform Evented interface.

- src/orbit-store/store.js
- src/orbit/coordinator.js
- src/orbit/source.js
- src/orbit/transform/log.js
- test/tests/orbit-store/unit/store-test.js
- test/tests/orbit/unit/source-test.js
- test/tests/orbit/unit/transform-log-test.js
By switching from a plain Array to an Immutable.List, we can emit events from TransformLog that contain the previous state.
This allows us to remove the clumsy methods `truncateHistory` and `clearHistory` on `Source` in favor of observing changes to the `transformLog`.
> Use an Immutable.List for state within TransformLog

- README.md
- package.json
In preparation for publishing to npm as `orbit-core` and extracting `orbit-jsonapi` and
`orbit-local-storage` as separate packages.
> Rename package and repo to `orbit-core`.

- src/action-queue.js
- src/action.js
- src/bucket.js
- src/coordinator.js
- src/source.js
- src/transform/log.js
- test/tests/support/fake-bucket.js
- test/tests/test-helper.js
- test/tests/unit/action-queue-test.js
- test/tests/unit/action-test.js
- test/tests/unit/coordinator-test.js
- test/tests/unit/interfaces/pullable-test.js
- test/tests/unit/interfaces/pushable-test.js
- test/tests/unit/interfaces/queryable-test.js
- test/tests/unit/interfaces/syncable-test.js
- test/tests/unit/interfaces/updatable-test.js
- test/tests/unit/source-test.js
- test/tests/unit/transform-log-test.js
Allow sources to persist their transient, in-memory state to a simple browser storage mechanism.
To be truly useful, this will require actual bucket implementations in orbit-local-storage and orbit-indexeddb.
> Introduce Bucket class.

- src/schema.js
- test/tests/unit/schema-test.js
After working through some issues with browser storage, it's become clear that schemas must be declared eagerly and can not support lazy hooks for defining models.
Schemas now support a `version` as well as an `upgrade` method (and corresponding event). This approach gives sources the opportunity to migrate their data if possible.
> Disallow lazy evaluation of schemas in favor of explicit schema upgrades.

- src/bucket.js
- src/source.js
Provide better encapsulation of some properties on `Bucket` and `Source` that should only be set via the `constructor`.
> Make some properties read-only.

- src/bucket.js
- src/schema.js
- test/tests/unit/bucket-test.js
Base `Bucket` class now has `namespace` and `version` properties, as well as an async `upgrade` method.
Also, `Schema` class has been refactored to better align its `upgrade` implementation.
> Enhance Bucket capabilities.

- src/query/terms.js
- test/tests/unit/query/builder-test.js
This PR adds support for sort expressions to QueryBuilder:
```js
qb.records('planet')
.sort([{ attribute: 'name', order: 'ascending' }])
```
> Add support for sort operator to QueryBuilder

- README.md
- build-support/build.js
- package.json
- src/transform/log.js
- test/tests/unit/transform-log-test.js
Immutable was not strictly needed in orbit-core. It was used within
TransformLog, but events that emitted prior log state have not proven
to be useful so far.
A dependency on an immutable library will likely be limited to 
orbit-store, where it’s truly needed within the Cache.
> Remove Immutable.js.

- src/lib/objects.js
- test/lib/object-test.js
`set` will perform a strict equality check to verify whether a mutation
is needed - and return `false` if not.
> `set` accessor returns whether mutation occurred

- packages/@orbit/core/src/index.ts
- packages/@orbit/core/src/schema.ts
- packages/@orbit/core/test/schema-test.js
- packages/@orbit/indexeddb/test/source-test.js
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/local-storage/test/source-test.js
Records should work everywhere in their sparse form, requiring only a
type and id. In the sparse form, it becomes ambiguous when to assign
default values. The concept of default values is probably best left
as a source-specific concern.
> Remove default values and normalization from Schema

- packages/@orbit/core/src/main.ts
- packages/@orbit/core/src/query.ts
- packages/@orbit/core/src/schema.ts
- packages/@orbit/core/src/transform.ts
- packages/@orbit/core/test/key-map-test.js
- packages/@orbit/core/test/schema-test.js
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
A global uuid generator on the `Orbit` namespace can be easily 
overridden with a custom function if desired.
This global uuid generator should be used everywhere by Orbit-related
libs instead of relying on a direct import of `uuid` from @orbit/utils.
> Introduce Orbit.uuid

- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/test/schema-test.ts
- packages/@orbit/store/src/cache/operation-processors/cache-integrity-processor.ts
- packages/@orbit/store/src/cache/operation-processors/schema-consistency-processor.ts
Removes modelDefaults to discourage dynamic schema creation. It will be
more performant for schemas to be defined fully at build time.
Also, removes methods `modelDefinition`, `keyDefinition`, and
`relationshipDefinition` in favor of direct access to the `models`
dictionary.
> Simplify Schema

- packages/@orbit/jsonapi/src/lib/queries.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
Ensure that attributes are properly serialized when they are included in
`sort` and `filter` queries as params.
> JSONAPI: Properly serialize sort and filter query params

- packages/@orbit/coordinator/src/coordinator.ts
- packages/@orbit/coordinator/test/coordinator-test.ts
Make `coordinator.deactivate()` safe to call regardless of the state of 
the coordinator.
> Allow coordinator to be deactivated when inactive

- packages/@orbit/store/src/cache/patch-transforms.ts
- packages/@orbit/utils/src/objects.ts
- packages/@orbit/utils/test/object-test.js
This brings `merge` inline with lodash’s implementation and most developers’
expectations.
> BREAKING: `merge` util no longer clones base object, allows for multiple sources

- packages/@orbit/data/src/operation.ts
- packages/@orbit/data/src/transform-builder.ts
- packages/@orbit/data/test/operation-test.ts
- packages/@orbit/data/test/transform-builder-test.ts
- packages/@orbit/indexeddb/src/lib/transform-operators.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/jsonapi/test/lib/transform-requests-test.ts
- packages/@orbit/local-storage/src/lib/transform-operators.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/store/src/cache/inverse-transforms.ts
- packages/@orbit/store/src/cache/operation-processors/cache-integrity-processor.ts
- packages/@orbit/store/src/cache/operation-processors/schema-consistency-processor.ts
- packages/@orbit/store/src/cache/patch-transforms.ts
- packages/@orbit/store/test/cache-test.ts
- packages/@orbit/store/test/cache/operation-processors/cache-integrity-processor-test.ts
- packages/@orbit/store/test/cache/operation-processors/schema-consistency-processor-test.ts
Provides consistency between transform and query operations.
[Closes #291]
> BREAKING: Rename transform operators that deal with relationships

- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/queryable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-test.ts
- packages/@orbit/store/src/cache.ts
- packages/@orbit/store/src/store.ts
- packages/@orbit/store/test/cache-test.ts
- packages/@orbit/store/test/store-test.ts
These builders will be instantiated on first access, so there’s no
additional overhead to keeping them on every Source.
Furthermore, builders can be passed as settings, which simplifies 
sharing of builders for greater efficiency.
> Add queryBuilder and transformBuilder to Source

- packages/@orbit/data/src/operation.ts
- packages/@orbit/data/src/record.ts
- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/test/operation-test.ts
- packages/@orbit/data/test/record-test.ts
- packages/@orbit/indexeddb/src/lib/transform-operators.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
- packages/@orbit/jsonapi/test/lib/transform-requests-test.ts
- packages/@orbit/local-storage/src/lib/transform-operators.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/store/src/cache.ts
- packages/@orbit/store/src/cache/inverse-relationship-accessor.ts
- packages/@orbit/store/src/cache/inverse-transforms.ts
- packages/@orbit/store/src/cache/operation-processors/cache-integrity-processor.ts
- packages/@orbit/store/src/cache/operation-processors/operation-processor.ts
- packages/@orbit/store/src/cache/operation-processors/schema-consistency-processor.ts
- packages/@orbit/store/src/cache/patch-transforms.ts
- packages/@orbit/store/src/cache/query-operators.ts
- packages/@orbit/store/src/cache/record-identity-map.ts
- packages/@orbit/store/src/cache/relationship-accessor.ts
- packages/@orbit/store/test/cache-test.ts
- packages/@orbit/store/test/cache/operation-processors/cache-integrity-processor-test.ts
- packages/@orbit/store/test/cache/operation-processors/schema-consistency-processor-test.ts
- packages/@orbit/store/test/cache/relationship-accessor-test.ts
Relationships will no longer be normalized to `type:id` string 
identifiers, like `planet:earth`. Instead they will remain in expanded
`{ type, id }` form, like `{ type: 'planet', id: 'earth' }`.
This change is fairly mechanical in most places, but required extensive
changes in @orbit/store, such as the introduction of a new 
RecordIdentityMap, RelationshipAccessor, and 
InverseRelationshipAccessor.
> BREAKING: Normalize relationship data to conform to JSONAPI spec

- packages/@orbit/core/src/main.ts
- packages/@orbit/indexeddb-bucket/src/bucket.ts
- packages/@orbit/indexeddb-bucket/src/lib/indexeddb.ts
- packages/@orbit/indexeddb/src/lib/indexeddb.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/jsonapi/test/support/jsonapi.ts
- packages/@orbit/jsonapi/test/support/orbit-setup.ts
- packages/@orbit/local-storage-bucket/src/bucket.ts
- packages/@orbit/local-storage-bucket/src/lib/local-storage.ts
- packages/@orbit/local-storage/src/lib/local-storage.ts
- packages/@orbit/local-storage/src/lib/pull-operators.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/local-storage/test/support/local-storage.ts
Introduce a new `globals` member on the main `Orbit` export.
`Orbit.globals` will be assigned to either `self`, `global`, `this`, 
or `{}` (checked in that priority). This approach to globals checking
matches the one used by underscore.js.
Packages now use `Orbit.globals.x` instead of `self.x` when checking
for any global variable.
Custom overrides, such as `Orbit.Promise`, should still be done as
before.
[Closes #434]
> Improve globals support

- packages/@orbit/data/src/record.ts
- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/data/src/transform-builder.ts
- packages/@orbit/data/test/schema-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/data/test/source-test.ts
- packages/@orbit/data/test/transform-builder-test.ts
- packages/@orbit/store/src/cache.ts
- packages/@orbit/store/src/cache/patch-transforms.ts
- packages/@orbit/store/src/index.ts
- packages/@orbit/store/src/store.ts
- packages/@orbit/store/test/cache-test.ts
- packages/@orbit/store/test/store-test.ts
The signature of `Updatable#update` has been changed to return `Promise<any>` instead of `Promise<void>`. This improves the DX of calling `update` directly by allowing results to be returned. See #439 for motivation.
The only standard source that implements `Updatable` is the `Store`, which now returns the record, or records, that result from an update.
When performing a single update operation, the primary data will be returned directly:
```javascript
return store.update(t => t.addRecord(jupiter))
.then(record => {
// record = jupiter 
});
```
When performing an update that involves several operations, the primary data will be returned as an array:
```javascript
return store.update(t => [t.addRecord(jupiter), t.addRecord(earth)])
.then(records => {
// records = [jupiter, earth]
});
``` …
> Allow Updatable#update to return resultant data (just like Queryable)

- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/syncable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/syncable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
After `beforeX` has been settled, it’s possible that the transform has
already been applied to a source. In that case, we can avoid further
processing.
This should improve performance and consistency in pessimistic update
(i.e. blocking) scenarios.
> Short circuit sync, push, and update calls if possible

- packages/@orbit/data/src/key-map.ts
- packages/@orbit/data/test/key-map-test.ts
* Avoids creating mappings when either ID or key is null / undefined
* Now uses two separate maps for `idsToKeys` and `keysToIds` to reduce the depth of sets/gets
> Improve efficiency and correctness of KeyMap

- packages/@orbit/store/src/cache.ts
- packages/@orbit/store/src/cache/patch-transforms.ts
- packages/@orbit/store/test/cache-test.ts
When records are added, replaced, or have their keys updated, the 
Cache’s keyMap should be updated.
> Store: Ensure that keyMap is updated

- packages/@orbit/data/src/key-map.ts
- packages/@orbit/data/test/key-map-test.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/local-storage/src/lib/pull-operators.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/local-storage/test/source-test.ts
Introduce KeyMap#reset for clearing a key map (especially useful for testing)
Ensure that IndexedDB and LocalStorage sources add records to their key maps, if one has been assigned.
> Key mapping improvements

- packages/@orbit/jsonapi/src/jsonapi-source.ts
There was an issue in `JSONAPISource#fetch` that caused an extra `JSONAPISource#handleFetchResponse` function call with a null argument, when there is a timeout and the `Orbit#fetch` call rejects.
I noticed this while developing an Orbit app with Angular. I'm not sure how to add unit test for this without Zone.js, since the TypeError is thrown after the promise has already been rejected before the `JSONAPISource#handleFetchResponse` function call.
> Fix issue in JSONAPISource#fetch error handling

- packages/@orbit/data/src/exception.ts
- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/test/schema-test.ts
- packages/@orbit/store/src/cache/inverse-relationship-accessor.ts
- packages/@orbit/store/src/cache/operation-processors/cache-integrity-processor.ts
- packages/@orbit/store/src/cache/operation-processors/schema-consistency-processor.ts
Switching this API to a method allows us to give better, earlier error messages when a model definition is missing.
Schema#models is still around as a private member so its only breaking in the sense of TypeScript type errors.
> Add Schema#getModel

- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/local-storage/src/lib/transform-operators.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/local-storage/test/source-test.ts
Any update operation should be possible in browser storage, including
updates to records’ attributes, keys, and relationships even if those 
records are not yet present. These updates should result in a sparse 
representation of the record.
> Ensure that IndexedDB and LocalStorage sources can perform sparse updates

- packages/@orbit/data/src/operation.ts
- packages/@orbit/store/src/cache.ts
- packages/@orbit/store/src/cache/operation-processors/operation-processor.ts
- packages/@orbit/store/src/cache/operation-processors/schema-validation-processor.ts
- packages/@orbit/store/test/cache/operation-processors/schema-validation-processor-test.ts
This new operations processor leverages a new validate hook (also added in this PR) to validate whether an operation is compatible with the schema.  With this implementation we only check that the record's type has an associated model definition in the schema, but in the future we may want to validate relationships and attributes.
I also fixed a type that was unexpectedly popping up null in the tests.
> Schema validation processor

- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/test/schema-test.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
Prior to this PR, if your JSON API response contained attributes or relationships that were not defined in your schema you would get unclear errors.
This PR changes the behaviour of the JSON API serializer so that unknown attributes and relationships are simply ignored.
> JSONAPISerializer should ignore attrs/rels not defined in the schema

- packages/@orbit/data/src/record.ts
- packages/@orbit/indexeddb/src/lib/transform-operators.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/local-storage/src/lib/transform-operators.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/store/src/cache/patch-transforms.ts
Fixes the handling of the `replaceRecord` operation in the IndexedDB and LocalStorage sources.
Prior to this PR, `replaceRecord` would complete clobber the existing record. This PR changes that behaviour that so that it merges the new fields into the old fields.
> Fix replaceRecord handling for IndexedDB and LocalStorage

- packages/@orbit/store/src/store.ts
- packages/@orbit/store/test/store-test.ts
When forking, the base store is stashed in the fork, as well as the
`forkPoint`, which is the `head` pointer of the base store’s log.
> Allow base store to be passed as Store constructor option

- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-test.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/store/src/cache.ts
- packages/@orbit/store/src/cache/inverse-relationship-accessor.ts
- packages/@orbit/store/src/cache/operation-processors/operation-processor.ts
- packages/@orbit/store/src/cache/relationship-accessor.ts
- packages/@orbit/store/src/store.ts
- packages/@orbit/store/test/cache-test.ts
- packages/@orbit/store/test/store-test.ts
All sources can now implement an `upgrade` method that upgrades them to the latest version of the schema.
By default, `Source#upgrade` will be invoked automatically whenever the schema emits an `upgrade` event. However, sources can explicitly opt-out of automatic upgrades via the `autoUpgrade: false` option. It is still possible to manually call `Source#upgrade` to provide finer control of the process.
> Provide standard approach for sources to respond to schema upgrades

- packages/@orbit/core/src/main.ts
in some contexts like react native `global.global` does not exist so orbit doesn't work because it can't find `Promise`. Also that `this` (hard)compiles to `undefined` so I removed it.
> globals react-native support

- packages/@orbit/store/src/cache.ts
Resolves the following error when TS compiler is configured with `noImplicitAny` is `true`.
```
node_modules/@orbit/store/dist/types/cache.d.ts
(43,27): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.
```
> Add explicit any type annotation to args

- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-test.ts
It currently does not seem possible to inject the `autoProcess` setting of a TaskQueue from any extension of the `Source` class.  The changes in this PR support the injection of any of the `TaskQueueSettings` for both the `requestQueue` and `syncQueue` of a `Source`.
> Allow for injection of task queue settings in Source initialization

- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/task-queue-test.ts
The result of `push` should not be dependent upon all processing being completed, nor should it be impacted by errors that occur while processing other tasks.
Fixes #496
> TaskQueue#push must return the result of processing the pushed task

- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/task-queue-test.ts
Aligns `TaskQueue#retry` with `TaskQueue#push`, in that the result of processing the retried task is returned rather than the result of invoking `process`.
Also fixes `TaskQueue#skip` to only continue processing when `autoProcess = true`.
> Correct TaskQueue#retry and TaskQueue#skip

- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
The addition of the `charset` media type param should not be necessary, nor should it be the default.
> Use bare jsonapi media type by default for content-type

- packages/@orbit/coordinator/src/strategies/connection-strategy.ts
- packages/@orbit/coordinator/src/strategies/sync-strategy.ts
- packages/@orbit/coordinator/test/strategies/request-strategy-test.ts
It should receive the `query` object just as the `action` function does.
> Allow blocking to be a function

- package-lock.json
- packages/@orbit/data/src/query-expression.ts
- packages/@orbit/data/src/query-term.ts
- packages/@orbit/data/test/query-builder-test.ts
- packages/@orbit/jsonapi/src/lib/pull-operators.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/store/src/cache/query-operators.ts
- packages/@orbit/store/test/cache-test.ts
Continuation of #514 
For not it assumes relationships are never polymorphic.
Urls:
- `relatedRecord` with a single record: `/moons?filter[planet]=earth`
- `relatedRecord` with a multiple records: `/moons?filter[planet]=earth,mars`
- `relatedRecords` with a multiple records: `/planets?filter[moons]=phobos,deimos`
The `relatedRecords` throws an error if the the operation !== "equal".
> Allow to filter by relationships in jsonapi

- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/src/lib/pull-operators.ts
- packages/@orbit/jsonapi/src/lib/query-params.ts
- packages/@orbit/jsonapi/src/lib/request-settings.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/jsonapi/test/lib/query-params-test.ts
- packages/@orbit/utils/src/deprecate.ts
- packages/@orbit/utils/src/objects.ts
- packages/@orbit/utils/test/object-test.js
The `FetchSettings` interface has been expanded to include the full-range of [options available for `fetch`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch).
The `JSONAPISource` can now accept a `defaultFetchSettings` option that will be applied to all requests. Note that the `Content-Type` header can be specified and it will be removed for requests with no content.
Specifying `defaultFetchSettings.headers` is now preferred over `defaultFetchHeaders`, which has been deprecated. Similarly, `defaultFetchSettings.timeout` deprecates `defaultFetchTimeout`.
The full range of fetch settings can also be specified on a per-request basis, as an option to a `Query` or `Transform`. These settings should be specified as options under `sources.[sourceName]`. For …
> [JSONAPI] Allow global and per-request fetch settings

- packages/@orbit/utils/src/objects.ts
- packages/@orbit/utils/test/object-test.js
Objects and arrays in source objects should always be cloned, never copied, into the base object.
Fixes #519
> `merge` and `deepMerge` should use clone

- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
Introduces @jembezmamy's test from #538 that shows that this problem was resolved thanks to @cibernox's work in #536.
Closes #538
> Add test for updating remote key within a single transform

- packages/@orbit/local-storage/src/lib/pull-operators.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/local-storage/test/support/local-storage.ts
When using the localStorage source and bucket at the same time, pulling the source would mistakenly create addRecord operations out of bucket entries, i.e. treat `orbit-bucket/*` keys as records.
> Fix LS-source interfering with LS-bucket

- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
JSONAPI allows server to return [new data in response to PATCH request](http://jsonapi.org/format/#crud-updating-responses-200). Currently Orbit ignores these updates. I added this function by reusing the code that handles POST requests.
> Apply changes returned by a server after PATCH request

- packages/@orbit/jsonapi/src/lib/query-operators.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
`remote.query()` unintentionally combined primary and side loaded data into a single array and thus also retuned the included data with the primary data.
> fix remote.query() with side loaded data

- packages/@orbit/immutable/src/immutable-map.ts
- packages/@orbit/immutable/test/immutable-map-test.ts
Introduce new methods to `ImmutableMap`:
* `entries`
* `clear`
* `setMany`
* `removeMany`
`setMany` and `removeMany` are more efficient than calling `set` or `remove` multiple times.
> Expand capabilities of ImmutableMap

- packages/@orbit/coordinator/src/strategies/connection-strategy.ts
- packages/@orbit/coordinator/src/strategies/event-logging-strategy.ts
- packages/@orbit/coordinator/test/strategies/event-logging-strategy-test.ts
- packages/@orbit/core/src/bucket.ts
- packages/@orbit/core/src/evented.ts
- packages/@orbit/core/src/index.ts
- packages/@orbit/core/src/log.ts
- packages/@orbit/core/src/notifier.ts
- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/evented-test.ts
- packages/@orbit/core/test/notifier-test.ts
- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/store/src/store.ts
Event listeners no longer need to be able to support an explicit `binding`, when the listeners themselves can be directly bound instead (if necessary).
Also, explicitly defines a `Listener` interface for better typings (vs. the generic `Function`).
> Define Listener interface and remove support for explicit binding object in listeners

- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
In an attempt to be more forgiving of server responses, the JSONAPISource will attempt to parse `Content-Type: application/json` as if it is compliant JSON:API. This eliminates a common error developers hit when using the JSONAPISource.
In order to be more strict and revert to the previous behavior, override the `responseHasContent` method.
Closes #487
> [jsonapi] Consider application/json to be valid content

- packages/@orbit/coordinator/src/coordinator.ts
- packages/@orbit/coordinator/src/strategies/connection-strategy.ts
- packages/@orbit/coordinator/src/strategies/sync-strategy.ts
- packages/@orbit/coordinator/src/strategy.ts
- packages/@orbit/core/src/assert.ts
- packages/@orbit/core/src/deprecate.ts
- packages/@orbit/core/src/evented.ts
- packages/@orbit/core/src/log.ts
- packages/@orbit/core/src/main.ts
- packages/@orbit/core/src/notifier.ts
- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/queryable.ts
- packages/@orbit/data/src/source-interfaces/syncable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/indexeddb-bucket/src/bucket.ts
- packages/@orbit/indexeddb/src/cache.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/src/lib/request-settings.ts
- packages/@orbit/local-storage-bucket/src/bucket.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/store/src/store.ts
- packages/@orbit/utils/src/index.ts
By exposing `assert` and `deprecate` only on the global `Orbit` atom, these methods can be more easily overridden and tested for specific builds.
Correct usage is now:
```ts
import Orbit from '@orbit/core'; // or '@orbit/data'
const { assert, deprecate } = Orbit;
```
[BREAKING] Removes `assert` and `deprecate` exports from `@orbit/utils` to avoid potential confusion.
> [BREAKING] Expose assert + deprecate only on OrbitGlobal

- packages/@orbit/coordinator/src/strategies/connection-strategy.ts
- packages/@orbit/coordinator/src/strategies/request-strategy.ts
- packages/@orbit/coordinator/test/strategies/request-strategy-test.ts
- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/queryable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/queryable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
Request "hints" are a new feature that allows event listeners to influence how an action is performed by a primary source. For instance, hints could allow `store.query()` to return results with the precise order and filtering dictated by another source, such as the `JSONAPISource`.
Hints are now available to every interface that participates in the [request flow](https://orbitjs.com/v0.15/guide/data-flows.html), including: `Pullable`, `Pushable`, `Queryable`, and `Updatable`.
A new `hints` argument, initialized as an empty object, is now passed to every `before` listener as a second argument. Listeners can provide “hints” by adding members to this object that will enable the source to fulfill the request. The `hints` object is then passed as a second argument to the source's internal …
> Introduce "hints" for requests

- packages/@orbit/store/src/store.ts
- packages/@orbit/store/test/store-test.ts
When a `Store` is provided hints from `beforeQuery` listeners, it will now use those hints to influence the results returned from `query`.
Applies when `hints.data` is set to `RecordIdentity | RecordIdentity[]`.
> [store] Support query hints

- packages/@orbit/data/src/record.ts
- packages/@orbit/jsonapi/src/jsonapi-document.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
This change should be sufficient to ensure that links are processed as part of resource deserialization.
Additional work will be required to ensure that links are followed when processing additional requests.
Closes #509
> Define Link interface and links objects (refactor of #509)

- packages/@orbit/data/src/record.ts
- packages/@orbit/jsonapi/src/jsonapi-document.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
Allow meta data everywhere it is allowed in JSON:API: the top-level document, records, relationships, and links.
Where `meta` is allowed, ensure it is properly typed as a dictionary object (rather than just `any`).
Additional work will be needed to add operations that mutate individual meta data members.
> Expand areas in which meta data is allowed

- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
A "204 No Content" response has by definition no content, even if the response includes a supported Content-Type header.
FWIW, I came across this because Mirage was returning a `DELETE` request by default with a 204 response with `Content-Type` set to `application/json`. This lead to a `JSON.parse` error, trying to parse an empty body. Probably doesn't make too much sense to return a `Content-Type` for a 204 response (filed https://github.com/samselikoff/ember-cli-mirage/pull/1481), but also I didn't find any reference stating that this is against the spec...
> Always treat a 204 response as having no content

- packages/@orbit/jsonapi/package.json
- packages/@orbit/jsonapi/src/index.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/src/lib/query-operators.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/src/record-document.ts
- packages/@orbit/jsonapi/src/resource-document.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/serializers/src/serializer.ts
* `JSONAPISerializer#serializeDocument` is deprecated in favor of `serialize`
* `JSONAPISerializer#deserializeDocument` is deprecated in favor of `deserialize`
* `DeserializedDocument` interface is deprecated in favor of `RecordDocument`
* `JSONAPIDocument` interface is deprecated in favor of `ResourceDocument`
> JSONAPISerializer implements new Serializer interface

- packages/@orbit/data/src/schema.ts
- packages/@orbit/jsonapi/Brocfile.js
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
Serializers can now be registered in the JSONAPISerializer and will be used to serialize/deserialize attribute values according to the `type` in the schema.
By default, all the standard serializers from `@orbit/serializers` are registered. In addition, custom serializers can be registered.
Furthermore, the `AttributeDefinition` interface (used within the `Schema`) has been expanded to include:
* `serializationOptions`
* `deserializationOptions`
These options can help specialize a serializer for the given attribute `type`.
Here's an example usage, taken from the tests:
```ts
const modelDefinitions: Dict<ModelDefinition> = {
person: {
attributes: {
name: { type: 'string' },
birthday: { type: 'date' },
birthtime: { type: 'datetime' },
height: { 
type: 'distance', 
serializationOptions: { …
```
> [jsonapi] Use new serializers for serializing / deserializing attribute values

- packages/@orbit/record-cache/src/operators/async-query-operators.ts
- packages/@orbit/record-cache/src/operators/sync-query-operators.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
This PR is based on #603 and extends the fix for `SyncRecordCache` to apply to `AsyncRecordCache` as well.
Furthermore, a related set of bugs is resolved, in which `findRelatedRecord` and `findRelatedRecords` should throw a `RecordNotFoundException` when the _primary_ record can not be found in a cache. This makes them consistent with `findRecord`.
Closes #603
> Extends #603 to fix related errors

- packages/@orbit/integration-tests/.npmignore
- packages/@orbit/integration-tests/Brocfile.js
- packages/@orbit/integration-tests/LICENSE
- packages/@orbit/integration-tests/README.md
- packages/@orbit/integration-tests/package-lock.json
- packages/@orbit/integration-tests/package.json
- packages/@orbit/integration-tests/test/.eslintrc.js
- packages/@orbit/integration-tests/test/store-jsonapi-clientid-pessimistic-test.ts
- packages/@orbit/integration-tests/test/store-jsonapi-remoteid-optimistic-test.ts
- packages/@orbit/integration-tests/test/store-jsonapi-remoteid-pessimistic-test.ts
- packages/@orbit/integration-tests/test/support/jsonapi.ts
- packages/@orbit/integration-tests/testem.json
- packages/@orbit/integration-tests/tsconfig.tests.json
This is a private package used for testing interactions among the core orbit packages.
It initially contains several variants on coordinating mutations between a store and a remote JSONAPISource. This suite should expand quite a bit over time.
> Add integration-tests package

- packages/@orbit/indexeddb/src/cache.ts
- packages/@orbit/local-storage/src/cache.ts
Persisting sources should not drop all data on initialize. Introduced in the following commit
https://github.com/orbitjs/orbit/commit/838dcc6b74297b647e64256b74dfa444ca2fbae2
> Do not reset persisting sources on initalize

- packages/@orbit/indexeddb/src/cache.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
`IndexedDB` source clobber parent record relationship when one of the members of the given relationship is removed. I added a `record-cache` and `local-storage` tests to show that the problem is scoped to `IndexedDB` source.
> RemoveRecord when part of has many relationship should not clobber the whole relationship in IndexedDB source

- packages/@orbit/jsonapi/src/jsonapi-source.ts
This makes overriding `fetch` method on the source easier. For example I want to replace timeout behaviour with cancelable `fetch` so just replacing `fetch` implementation is not enough. But if I replace `fetch` method on the source I have no way to serialise query params with the internal orbit implementation.
> Extract appendQueryParams in its own method

- packages/@orbit/record-cache/src/operators/async-inverse-patch-operators.ts
- packages/@orbit/record-cache/src/operators/sync-inverse-patch-operators.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
Fixes #624
Given my superficial knowledge here, please double check twice that this is the right place and way to fix it! :)
It does however fix the added test, which was failing before, and it also fixes the actual error I saw in our app (when using the patched `record-cache` as a linked package).
> Fix updating an empty record with an empty relationship

- packages/@orbit/data/src/exception.ts
- packages/@orbit/data/src/schema.ts
- packages/@orbit/record-cache/src/operation-processors/async-schema-validation-processor.ts
- packages/@orbit/record-cache/src/operation-processors/sync-schema-validation-processor.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/operation-processors/schema-validation-processor-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
Retry of #626 with branches properly rebased.
Aims to get the ball rolling on #475 .
Allows the model property in the relationship definition to be a string or an array of strings
Add relationship validation to the schema-validation-processor.
This validations ensure that a relationships being added/replaced must be specified in the schema model definition.
It also ensures that relationship being added/replaced must adhere to the types specified in the model property on the relationship definition.
> Polymorphic Relationships

- packages/@orbit/integration-tests/test/store-jsonapi-remoteid-optimistic-test.ts
- packages/@orbit/integration-tests/test/store-jsonapi-remoteid-pessimistic-test.ts
- packages/@orbit/jsonapi/src/index.ts
- packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/src/jsonapi-url-builder.ts
- packages/@orbit/jsonapi/src/lib/query-operators.ts
- packages/@orbit/jsonapi/src/lib/request-settings.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-request-processor-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/jsonapi/test/jsonapi-url-builder-test.ts
- packages/@orbit/jsonapi/test/lib/request-settings-test.ts
- packages/@orbit/jsonapi/test/lib/transform-requests-test.ts
- packages/@orbit/jsonapi/test/support/jsonapi.ts
Implementation of #628.
TODO List:
> Introduce JSONAPIRequestProcessor

- packages/@orbit/coordinator/package.json
- packages/@orbit/core/package.json
- packages/@orbit/data/package.json
- packages/@orbit/identity-map/package.json
- packages/@orbit/immutable/package.json
- packages/@orbit/indexeddb-bucket/package.json
- packages/@orbit/indexeddb/package.json
- packages/@orbit/jsonapi/package.json
- packages/@orbit/local-storage-bucket/package.json
- packages/@orbit/local-storage/package.json
- packages/@orbit/memory/package.json
- packages/@orbit/record-cache/package.json
- packages/@orbit/serializers/package.json
- packages/@orbit/store/package.json
- packages/@orbit/utils/package.json
The `module` field for all Orbit packages has been pointing to the ES5 transpiled build.
Instead of deoptimizing build size and language features, Orbit will now point to the latest ES builds (currently the ES2017 target of the TS compiler).
If you wish to continue to use the ES5 builds, please adjust your app's build processes to ensure that you grab the right distribution from `dist`.
> Update language level of module target to es2017

- packages/@orbit/coordinator/package.json
- packages/@orbit/core/package.json
- packages/@orbit/data/package.json
- packages/@orbit/identity-map/package.json
- packages/@orbit/immutable/package.json
- packages/@orbit/indexeddb-bucket/package.json
- packages/@orbit/indexeddb/package.json
- packages/@orbit/jsonapi/package.json
- packages/@orbit/local-storage-bucket/package.json
- packages/@orbit/local-storage/package.json
- packages/@orbit/memory/package.json
- packages/@orbit/record-cache/package.json
- packages/@orbit/serializers/package.json
- packages/@orbit/store/package.json
- packages/@orbit/utils/package.json
The v0.16-beta.6 release came with an unacceptable number of breakages due to changing the default `module` target from es5 to es2017.
I'm going to revert this change and wait until at least v0.17 to change the target.
> Revert "Update language level of module target to es2017"

- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
- prior to this commit, attempting to serialize a record with a attribute not specified in the schema caused an error:
`undefined is not an object (evaluating 'attrOptions.type')`
> When serializing, exclude attributes & relationships not in the schema

- packages/@orbit/integration-tests/test/support/jsonapi.ts
- packages/@orbit/jsonapi/test/support/jsonapi.ts
The right syntax to generate a Response without a body is `new Response(null, initOpts)`.
Before this changes, all those invocations were generating 200 OK responses:
```
jsonapiResponse(404)
jsonapiResponse({status: 404});
jsonapiResponse({status: 404}, null);
jsonapiResponse({status: 404, headers: { 'Content-Type': 'application/vnd.api+json' }, null);
```
If fact this `jsonapiResponse({ status: 204 })` was generating a 200 OK response too.
> Fix generation of empty responses on tests

- packages/@orbit/data/src/query-term.ts
- packages/@orbit/data/test/query-builder-test.ts
Previously, the QueryBuilder assumed that a filter specifier without a `kind` was an attribute filter. This was true even if no attribute property was present, which could never work. This silently failed to filter anything. Furthermore, an end-developer used to other filter APIs might attempt to pass something like `{ firstName: 'Luke' }` to filter, which would fall into this silent failure path.
This commit ensures that an attribute is specified before assuming the filter is an attribute filter. In the example above, that means the well-meaning and otherwise intelligent and good-looking end developer will receive a helpful error instead of, say, shipping a non-functional filter to production.
@mattmcmanus / @lukemelia
> Throw when invalid filter expression.

- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-operations-test.ts
depends on #639 
In the future we will probably want `serializeQueryExpression` and `serializeRequest`
with something like (hypothetical code):
```ts
serializeRequest(request: Request): ResourceOperationsDocument {
const operations = request.operations.map(operation => {
if (isQueryExpression(operation)) {
return this.serializeQueryExpression(operation);
} else {
return this.serializeOperation(operation);
}
});
return { operations };
}
```
`serializeOperation` should be needed no matter what
>  Add serializeOperation to @orbit/jsonapi

- packages/@orbit/data/src/source-interfaces/syncable.ts
- packages/@orbit/data/src/transform.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/src/lib/request-settings.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/operators/async-inverse-patch-operators.ts
- packages/@orbit/record-cache/src/operators/sync-inverse-patch-operators.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/utils/src/objects.ts
`Array.isArray` is a type guard in TS as opposed to the custom one. I think it is a good enough reason to switch.
> Use native isArray

- packages/@orbit/jsonapi/src/lib/query-operators.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/lib/query-operators-test.ts
- packages/@orbit/jsonapi/test/lib/transform-requests-test.ts
This is in order to help some people implementing custom sources and it will be also needed anyway as a building block when we decide on a public api to expose meta and links from sources.
> Expose meta and links from processors to source

- packages/@orbit/core/src/task-processor.ts
- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/task-processor-test.ts
- packages/@orbit/core/test/task-queue-test.ts
Tasks in a `TaskQueue` may be cancelled via the `skip`, `clear`, or `shift` methods. The promises associated with any cancelled tasks should be settled via a rejection (if they haven't been settled already).
By default, settling is done with a default error, although a custom error may alternatively be passed as an argument.
Fixes #653
>  Ensure that cancelled tasks in queues have promises rejected 

- packages/@orbit/data/src/source.ts
It have been a mistake to include queue processing in deactivate. The queues might be configured with autoProcess: false or they may be paused with an error.
> Remove queues processing from deactivate

- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
Hints can be applied by a `beforeUpdate` listener to inform the results returned from calling `update` on a `MemorySource`.
The implementation aligns with the application of hints to `query`.
> [@orbit/memory] Support hints for `update`

- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/syncable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/syncable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
**This PR represents a breaking change for sources that implement `Updatable`, `Syncable`, `Pullable`, and `Pushable` interfaces.**
Sources are now responsible for doing the following in their internal implementation methods (e.g. `_update`, `_sync`, etc.):
* checking their `transformLog` for the requested transform to see if any work actually needs to be done.
* invoking `_transformed` for any transforms that are applied.
By moving these responsibilities to _source_ implementations, we allow more flexibility in implementations. For instance, `_update` can ignore re-applying transforms that may have been sync'd via `beforeUpdate` listeners, while still returning results that are specified via the `hints` argument.
**Note that all the standard sources have been updated to account for these …
> [BREAKING] Shift some responsibilities for transform-related interfaces to source implementations

- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/syncable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/syncable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/indexeddb/test/source-test.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/local-storage/test/source-test.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
This PR is based upon #678, and represents a very minor behavioral tweak to ensure that `Updatable` interfaces and hints will work even with custom-defined operations.
This PR clarifies that a singular result should be returned when `update` is called with a `Transform` that contains only one operation. Otherwise, an array of results should be returned.
For standard operations, this should not be a breaking change. However, if you've been defining your own custom operations that returned arrays together with hints in v0.16 beta, you'll want to test this change thoroughly.
> Standardize update responses

- packages/@orbit/coordinator/test/strategies/log-truncation-strategy-test.ts
- packages/@orbit/coordinator/test/strategies/sync-strategy-test.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/syncable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/data/test/source-test.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/local-storage/src/source.ts
- packages/@orbit/memory/src/memory-source.ts
Now that source implementations are more likely to be responsible for calling this method to let others receive `transform` events, the time is probably right to make it more ergonomic. It is a protected method in TS, which accomplishes the same goal of signaling to developers that it should only be invoked internally within sources.
> [DEPRECATION] Deprecate `_transformed` in favor of `transformed`

- packages/@orbit/memory/test/memory-cache-test.ts
- packages/@orbit/record-cache/src/operators/async-query-operators.ts
- packages/@orbit/record-cache/src/operators/sync-query-operators.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
Continues the work started in #701. 
Since records can be sparse, always treat `undefined` values as `undefined` rather than `null` or `[]` when filtering them. In other words, filters should ignore `undefined` values and never return a match.
Notes: 
* There is still an option to allow a special filter type for `undefined`, but this case should be handled distinctly.
* A follow up PR should consolidate the logic shared across sync / async query operators.
> Always ignore undefined values when filtering

- packages/@orbit/data/src/operation.ts
- packages/@orbit/data/test/operation-test.ts
- packages/@orbit/data/yarn.lock
Sometimes when I tried to update related record with null on a forked store, I was encountering an error: `Cannot destructure property 'type' of 'identity' as it is null` in `cloneRecordIdentity`.
It seems like a bug - `updateRecordReplaceHasOne` should also accept nulls, right?
I've added a test for this failing case and fixed it. I'm not sure if that's the best place for this fix... maybe this should be done in the `cloneRecordIdentity`?
> Allow mergeOperations to set null for hasOne relationship

- packages/@orbit/core/src/bucket.ts
- packages/@orbit/core/test/bucket-test.ts
- packages/@orbit/core/test/support/fake-bucket.ts
- packages/@orbit/data/test/support/fake-bucket.ts
- packages/@orbit/indexeddb-bucket/src/bucket.ts
- packages/@orbit/indexeddb-bucket/test/bucket-test.ts
- packages/@orbit/local-storage-bucket/src/bucket.ts
- packages/@orbit/local-storage-bucket/test/bucket-test.ts
This adds an abstract `clear()` method to `Bucket`. Implementations of a bucket would clear all the entries within it.
From #460:
>  It would be useful for implementing log out in a mobile app.
---
Closes #460
> Bucket.clear()

- packages/@orbit/coordinator/src/coordinator.ts
- packages/@orbit/coordinator/src/strategy.ts
- packages/@orbit/coordinator/test/coordinator-test.ts
- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/task-queue-test.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-test.ts
Implements the plan discussed in https://github.com/orbitjs/orbit/issues/725#issuecomment-590009540 to provide more deterministic control of source and strategy activation. Specifically, this PR does the following:
* When a source is configured with `autoActivate: false`, its request and sync queues are now instantiated with `autoProcess: false` by default. `Source#activate` will flip this flag and invoke `this.syncQueue.process()` and then `this.requestQueue.process()` (unless queue settings have been explicitly made that indicate that `autoProcess` should remain `false`).
* Strategies no longer activate sources by default in `activate`. Source activation is now done instead in `Coordinator#activate` after all strategies have been activated. Similarly, source deactivation is now done in …
> Improve control of source and strategy activation and deactivation

- packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
- packages/@orbit/jsonapi/src/lib/query-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
A response with status code 304 indicates that we already have the
latest, valid representation available.
Currently a response with this status results in an error. With this
change such a response is handled in a successful manner, which results
in a transform with no operations.
---
I am not fully familiar with all the concepts yet and pretty sure I am missing something. This is just my initial stab at addressing parts of #577 and putting this out there to get more input.
I am especially unsure about having a transform with no operations, which I guess should be no transform at all...
Appreciate pointers in any direction and happy to make changes.
> Handle 304 responses in jsonapi-request-processor

- packages/@orbit/data/src/record.ts
- packages/@orbit/data/test/record-test.ts
- packages/@orbit/memory/test/memory-cache-test.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
Improves the long overlooked `mergeRecords` function so that it properly accounts for `links`, `meta`, and `relationships`. This should ensure that updates are properly applied to cache-based sources.
The updated merging logic is as follows: 
* `meta` and `links` sections are replaced in their entirety rather than attempting to merge individual members of each. This ensures that there is not an inconsistent state within each section.
* `attributes` and `keys` sections are traversed, replacing individual fields.
* `relationships` are traversed, replacing at the nested `data`, `links`, and `meta` level.
Fixes #709
> Improve mergeRecords to better handle links, meta, and relationships

- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/index.ts
- packages/@orbit/record-cache/src/live-query/async-live-query.ts
- packages/@orbit/record-cache/src/live-query/live-query.ts
- packages/@orbit/record-cache/src/live-query/record-change.ts
- packages/@orbit/record-cache/src/live-query/sync-live-query.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
This a new proposition to introduce query observers. This one is not relying on any known interface such as `RX` or `async iterator`. It uses orbit events. It does expose an `LiveQuery` interface, but it is simply an object with a `subscribe` method with returns a subscription with an `unsubscribe` method.
The current one has a downside of looking like an `RX`/`Zen` Observable but not being one. I am worried it might confuse folks. One option I considered is to pass the callback directly to `liveQuery` method, but it makes it for a complex signature because of optional `options` and `id` arguments...
What do you think @dgeb?
> Implement live query on @orbit/record-cache

- packages/@orbit/data/src/record.ts
- packages/@orbit/data/test/record-test.ts
- packages/@orbit/memory/test/memory-cache-test.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
Improve `mergeRecords` to better handle links, meta, and relationships.
> Backport PR 735 to v0.16

- packages/@orbit/data/src/index.ts
- packages/@orbit/data/src/options.ts
- packages/@orbit/data/src/query.ts
- packages/@orbit/data/src/request.ts
- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/queryable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/src/transform.ts
- packages/@orbit/data/test/request-test.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/queryable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/jsonapi/src/index.ts
- packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/src/jsonapi-url-builder.ts
- packages/@orbit/jsonapi/src/lib/jsonapi-request-options.ts
- packages/@orbit/jsonapi/src/lib/query-requests.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/jsonapi/test/lib/jsonapi-request-options-test.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
This PR formalizes a `RequestOptions` interface, which can include general options at the root-level, as well as source-specific options nested within `sources`.
For example:
```
{
label: 'Find planets and their moons',
sources: {
remote: { include: 'moons' }
}
}
```
All options in the request-flow are now typed as `RequestOptions`.
This also adds a `requestOptionsForSource` method that transforms a `RequestOptions` object into a simple source-specific, flattened `Options` object. When run for the `remote` source `('requestOptionsForSource(options, 'remote')` on the `options` above, this would transform them into:
```
{
label: 'Find planets and their moons',
include: 'moons'
}
```
The expectation is that each source implementation will use this method to merge options into only the …
> Standardize request option handling

- packages/@orbit/jsonapi/src/lib/jsonapi-request-options.ts
- packages/@orbit/jsonapi/src/lib/query-requests.ts
- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
Allow the `url` of a request to be overridden for all queries and transforms.
Any `url` that's passed will form a base URL that may be further amended with query params if additional options are passed that would normally include query params. Note that the `url` itself may also include query params.
> [jsonapi] Support `url` request option

- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/memory/src/memory-source.ts
This is needed as otherwise it is impossible to pass cache settings to a source in TS. The only non-optional setting on a cache settings type is `schema` and it is set by the source before creating a cache instance.
> cache settings as part of source settings should be partial

- packages/@orbit/memory/test/memory-source-test.ts
- packages/@orbit/record-cache/src/operation-processors/utils/cache-integrity-utils.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
This resolves an issue uncovered by @derekwsgray in #760 in which cache integrity processors were mishandling relationship bookkeeping when an explicit `inverse` was not defined in the schema.
This removes the schema relationship check such that inverse relationships will always be tracked.
Part of the confusion is the somewhat overloaded term "inverse relationship". This should probably be clarified prior to v0.17 and this fix should be backported to v0.16.
Fixes #760
> Fix cache integrity processors' handling of relationships without explicit inverses.

- packages/@orbit/record-cache/src/operation-processors/utils/cache-integrity-utils.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
Fix cache integrity processors' handling of relationships without explicit inverses
Inverses of relationships must still be maintained even when no explicit inverse is included in a relationship definition.
> Backport PR 762 to v0.16

- packages/@orbit/jsonapi/src/index.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
This PR fixes an oversight in which the deprecated jsonapi-serializer module was no longer exported. This should be exported until it's removed in v0.18.
This PR also exposes methods on the `JSONAPISource` related to transform and query request processing, as well as the supporting lib modules, to allow for easier customization on a per-request level.
> Expand exports in @orbit/jsonapi

- packages/@orbit/data/src/query.ts
- packages/@orbit/data/src/transform.ts
- packages/@orbit/data/test/query-test.ts
- packages/@orbit/data/test/transform-test.ts
Instead of relying on an instanceof check, check for the presence of a coercion function.  `isQueryTerm` checks for `toQueryExpression`, while `isOperationTerm` checks for `toOperation`.
This allows for more flexibility in what is considered a "term" and is consistent with the strategy used by `isTransform` and `isQuery`.
> Improve flexibility of term handling when building queries and transforms

- packages/@orbit/jsonapi/src/serializers/jsonapi-serializer-builder.ts
- packages/@orbit/jsonapi/test/serializers/jsonapi-resource-serializer-test.ts
These types are often used for attributes with the expectation that they will be passed through "as-is". Registering them with this expectation should smooth over the transition to the new serializers.
> [jsonapi] Register `object` and `array` types to use NoopSerializer by default

- packages/@orbit/data/src/record.ts
- packages/@orbit/data/src/schema.ts
- packages/@orbit/data/src/transform-builder.ts
- packages/@orbit/data/test/transform-builder-test.ts
The new `UninitializedRecord` interface can be used when adding records with the `TransformBuilder`, which will transform them to full-fledged `Record`s via the `RecordInitializer`.
`RecordInitializer#initializeRecord` has been updated to be expected to return a `Record`, instead of just initializing the passed object. The old behavior is still supported but now deprecated.
These changes should clarify typings and eliminate the need to coerce new records (`as Record`) when adding them without an assigned `id`.
> Introduce UninitializedRecord interface, with optional `id`

- packages/@orbit/data/src/schema.ts
Orbit's standard packages no longer rely upon the `singularize` / `pluralize` inflectors defined in `Schema`.
These inflectors have been superseded by the more flexible and customizable inflectors defined in `@orbit/serializers`.
> Deprecate inflectors (singularize/pluralize) on Schema

- packages/@orbit/utils/src/objects.ts
These functions are no longer used within Orbit and should be removed in v0.18.
> Deprecate `merge`, `extend`, and `expose` utility fns

- packages/@orbit/memory/src/memory-cache.ts
Generally loading a large amount of records (e.g. 5000) with a relationship was very slow. The reason seems to be that with each `updateRecord` operation, the `finally` action for the `sync-cache-integrity-processor` processor took more and more time - in the end up to 3ms per relationship per operation. This is because it was deep cloning the list of inverse relationships each time, which grew with each time.
As discussed with @dgeb , changed to clone only the newly added relationship.
> Improve perf by cloning only newly added relationship

- packages/@orbit/data/src/request.ts
- packages/@orbit/data/src/response.ts
- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/queryable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/queryable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/integration-tests/test/store-jsonapi-clientid-pessimistic-test.ts
Removes the not-fully-implemented `includeSources` option from `RequestOptions`.
Other source responses, if returned in `beforeX` event handlers, will now always be included in full response objects. This simplifies the processing code and costs nothing in efficiency.
> Remove includeSources request option

- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-test.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-queryable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-updatable-test.ts
* Allows `defaultQueryOptions` and `defaultTransformOptions` to be modified, even after source instantiation.
* JSONAPISource: Deprecates `maxRequestsPer[Query/Transform]` in favor of `default[Query/Transform]Options.maxRequests`. This allows `maxRequests` to be a general per-query/transform option which can have a default value, or be set as an option at the query/transform level.
> Improve usage of transform / query options

- packages/@orbit/integration-tests/test/support/jsonapi.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-queryable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-updatable-test.ts
- packages/@orbit/jsonapi/test/support/jsonapi.ts
The new `parallelRequests` request option affects whether multiple requests made as part of a single query or transform will be processed in series or parallel. This allows multiple fetch calls to be invoked simultaneously. Previously, all requests were made serially.
By default, `parallelRequests` is `true` for queries (via `defaultQueryOptions`). However, because there's often a dependency order between operations in a single transform, `parallelRequests` is not set for transforms (via `defaultTransformOptions`).
Like all default options, these can be overridden on a per-request basis.
> JSONAPISource: Introduce parallelRequests option

- packages/@orbit/core/src/bucket.ts
- packages/@orbit/core/src/evented.ts
- packages/@orbit/core/src/log.ts
- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/evented-test.ts
- packages/@orbit/data/src/request.ts
- packages/@orbit/data/src/response.ts
- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
- packages/@orbit/data/src/source-interfaces/queryable.ts
- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/src/source.ts
- packages/@orbit/data/test/source-interfaces/pullable-test.ts
- packages/@orbit/data/test/source-interfaces/pushable-test.ts
- packages/@orbit/data/test/source-interfaces/queryable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/live-query/async-live-query.ts
- packages/@orbit/record-cache/src/live-query/sync-live-query.ts
- packages/@orbit/record-cache/src/record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/record-cache/test/async-record-cache-query-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-query-test.ts
- packages/@orbit/records/src/record-schema.ts
* Simplify decorated classes by using separate interface definitions to avoid defining redundant stub methods
* Overload method definitions to avoid needing `DataOrFullResponse` and `TransformsOrFullResponse` interfaces
* Use generics to allow more refined typing of return values
> Improve typings via separate interface definitions, overloaded methods, and more generics

- packages/@orbit/core/src/evented.ts
- packages/@orbit/core/test/evented-test.ts
- packages/@orbit/core/test/support/timing.ts
- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/local-storage/src/local-storage-cache.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/memory/src/memory-cache.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/records/src/record-schema.ts
- packages/@orbit/records/src/record-source.ts
- packages/@orbit/records/test/record-schema-test.ts
- packages/@orbit/records/test/support/timing.ts
The goal of this PR is to ensure that a call to `await schema.upgrade(settings)` will complete by the time all listeners (i.e. typically sources that share this schema) have completed their upgrades (which may occur async).
Listeners are invoked with a new `fulfillAll` method for `Evented` objects, which uses `Promise.all` to fulfill any promises that may be returned by listeners.
A cleanup pass was also made on sources to ensure that they all provide an async `upgrade` method.
> Ensure that schema + source upgrades are reliably async

- packages/@orbit/build/package.json
- packages/@orbit/coordinator/package.json
- packages/@orbit/core/package.json
- packages/@orbit/data/package.json
- packages/@orbit/identity-map/package.json
- packages/@orbit/immutable/package.json
- packages/@orbit/indexeddb-bucket/package.json
- packages/@orbit/indexeddb/package.json
- packages/@orbit/jsonapi/package.json
- packages/@orbit/local-storage-bucket/package.json
- packages/@orbit/local-storage/package.json
- packages/@orbit/memory/package.json
- packages/@orbit/record-cache/package.json
- packages/@orbit/records/package.json
- packages/@orbit/serializers/package.json
- packages/@orbit/utils/package.json
This setting should override the npm default private scope for publishing new org-scoped packages like `@orbit/records`.
See https://github.com/lerna/lerna/issues/1821#issuecomment-551393580
> Add publishConfig settings to package.json

- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/indexeddb/test/indexeddb-source-test.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/local-storage/test/local-storage-source-test.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
- packages/@orbit/record-cache/src/record-cache.ts
- packages/@orbit/record-cache/test/record-cache-test.ts
- packages/@orbit/records/src/record-source.ts
- packages/@orbit/records/test/record-source-test.ts
On source instantiation, caches will now be instantiated with any `defaultQueryOptions` and `defaultTransformOptions` passed as source settings (unless the corresponding options are explicitly set in `cacheSettings`).
Furthermore, these settings will be kept in sync when updated on the source.
> Ensure that query/transform options are shared between sources and their caches

- packages/@orbit/coordinator/src/coordinator.ts
- packages/@orbit/coordinator/test/coordinator-test.ts
Makes it possible (but entirely optional) to explicitly type the return from `getSource` and `getStrategy`. For example:
```
const source = coordinator.getSource<MySource>('backup');
const strategy = coordinator.getStrategy<MyStrategy>('sync');
```
> Coordinator: Allow generic typing of getStrategy & getSource

- packages/@orbit/record-cache/test/async-record-cache-update-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-update-test.ts
These tests are based on the `patch` tests, but also include tests to validate the new full response format.
> Fill in tests for `update` for sync+async caches

- packages/@orbit/indexeddb/test/indexeddb-source-updatable-test.ts
- packages/@orbit/local-storage/test/local-storage-source-updatable-test.ts
- packages/@orbit/memory/test/memory-source-updatable-test.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/operators/async-inverse-transform-operators.ts
- packages/@orbit/record-cache/src/operators/async-transform-operators.ts
- packages/@orbit/record-cache/src/operators/sync-inverse-transform-operators.ts
- packages/@orbit/record-cache/src/operators/sync-transform-operators.ts
- packages/@orbit/record-cache/src/record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/record-cache/test/async-record-cache-update-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-update-test.ts
`RecordCacheTransformOptions` now parallels `RecordCacheQueryOptions`.
The default behavior (raising no exceptions) is to treat updates as if to a sparse cache, filling in details as requested. By setting `raiseNotFoundException: true`, you can prevent transforms from being applied to records that do not yet exist in a cache.
> Introduce `raiseNotFoundException` option for transform requests

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/test/indexeddb-cache-test.ts
Perform multiple IDB operations (get/put/delete) simultaneously rather than serially for bulk operations. Only the last request needs an `onsuccess` handler. This approach is not only more performant but much more robust when applying very large (> 5000 record) updates.
---
This approach results in modest performance gains for IndexedDB. In addition, I'm working on providing much more significant gains via a transform buffer that allows for complex updates that involve many record types and relationships to be truly batched and performed in a single IDB transaction.
> Improve bulk IndexedDB performance

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/test/indexeddb-cache-test.ts
This fixes an issue with `IndexedDBCache#getInverseRelationshipsAsync` in which
the wrong index was being used to lookup items in the object store that
maintains inverse relationships (`__inverseRels__`).
This bug could result in the inability of the `AsyncCacheIntegrityProcessor` to
properly remove relationships when records themselves are removed.
The correct index, `relatedIdentity`, also needs to be added. This will need to be
handled for pre-existing databases with an IndexedDB migration.
> Fix IndexedDBCache getInverseRelationshipsAsync

- packages/@orbit/indexeddb/src/cache.ts
- packages/@orbit/indexeddb/src/source.ts
- packages/@orbit/indexeddb/test/cache-test.ts
:boom: **Important: Action is needed to correct the integrity of any pre-existing `@orbit/indexeddb` databases. See below.** :boom:
_Note: This issue has been written specifically for @orbit/indexeddb v0.16. If you're using v0.17 or later, see #823._
This PR fixes an issue with `IndexedDBCache#getInverseRelationshipsAsync` in which the wrong index was being used to lookup items in the object store that maintains inverse relationships (`__inverseRels__`). This issue may have prevented the `AsyncCacheIntegrityProcessor` from properly removing relationships when records were removed. Therefore, it's possible that your cache may contain extra "dead" relationships (i.e. relationships to records that have been removed).
This PR adds the missing index, `relatedIdentity`, to the object store …
> Backport PR 823 to v0.16

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
When the `relatedIdentity` index is missing on the inverse relationships object store, prevent a hard fail and instead add guidance with a `console.error` message.
> Add fallback and error logging guidance to improve PR 823

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/test/indexeddb-cache-update-test.ts
- packages/@orbit/indexeddb/test/support/setup.ts
- packages/@orbit/local-storage/src/local-storage-cache.ts
- packages/@orbit/local-storage/test/local-storage-cache-test.ts
- packages/@orbit/local-storage/test/local-storage-cache-update-test.ts
- packages/@orbit/local-storage/test/support/local-storage.ts
- packages/@orbit/local-storage/test/support/setup.ts
- packages/@orbit/memory/src/memory-cache.ts
- packages/@orbit/memory/test/memory-cache-test.ts
- packages/@orbit/memory/test/memory-cache-update-test.ts
- packages/@orbit/memory/test/support/setup.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/index.ts
- packages/@orbit/record-cache/src/record-accessor.ts
- packages/@orbit/record-cache/src/record-cache.ts
- packages/@orbit/record-cache/src/record-transform-buffer.ts
- packages/@orbit/record-cache/src/response.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/record-cache/test/async-record-cache-update-test.ts
- packages/@orbit/record-cache/test/support/example-async-record-cache.ts
- packages/@orbit/record-cache/test/support/example-sync-record-cache.ts
- packages/@orbit/record-cache/test/sync-record-cache-update-test.ts
- packages/@orbit/records/src/record-operation.ts
- packages/@orbit/records/src/record.ts
- packages/@orbit/records/test/record-operation-test.ts
- packages/@orbit/records/test/record-test.ts
As mentioned in #821, this PR introduces a new `RecordTransformBuffer` for applying updates to caches in a more atomic and performant manner.
The `RecordTransformBuffer` acts as a synchronous memory cache that is populated, tracks changes as an update is applied, and then returns a corresponding changeset that includes all the changes that can be applied at once to another source.
This buffered approach addresses the IndexedDB performance issues mentioned in #798 and also will be useful for local storage updates.
Using a buffer to apply changes will initially be opt-in, via the `useBuffer` option. Sources can also set this option for all transforms via `source.defaultTransformOptions = { useBuffer: true }`.
--- 
_Note: perf benchmarks will be added with a separate PR._
> Introduce RecordTransformBuffer for improving performance and atomicity of cache updates

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/indexeddb/test/indexeddb-source-test.ts
- packages/@orbit/local-storage/src/local-storage-cache.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/local-storage/test/local-storage-source-test.ts
- packages/@orbit/memory/src/memory-cache.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
All record-cache-based sources (memory, indexeddb, and local storage) now allow a `cacheClass` setting to be passed on construction. This allows for customization of cache behavior that may not be plausible via the other cache-related setting: `cacheSettings`.
> Allow record-cache-based sources to define a custom `cacheClass`

- packages/@orbit/data/src/source-interfaces/syncable.ts
- packages/@orbit/data/test/source-interfaces/syncable-test.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
- packages/@orbit/records/src/record-source-interfaces/record-syncable.ts
Adds support for calling `sync` with a function that expects a transform builder argument. Improves ergonomics of using `sync` directly.
Closes #796
> Support use of a transform builder in Syncable

- packages/@orbit/coordinator/src/strategy.ts
- packages/@orbit/core/src/deprecate.ts
- packages/@orbit/core/src/main.ts
- packages/@orbit/indexeddb-bucket/src/lib/indexeddb.ts
- packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/src/jsonapi-url-builder.ts
- packages/@orbit/jsonapi/src/serializers/jsonapi-resource-identity-serializer.ts
- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
- packages/@orbit/records/src/record-source.ts
`Orbit.debug` is set to `true` by default to improve awareness of deprecations and other debugging safeguards.
When `Orbit.debug` is set to `false`:
* Deprecations will be silenced.
* Schema validation processors won't be assigned  by default in record caches.
> Add debug setting to `Orbit` global

- packages/@orbit/data/src/source-interfaces/pullable.ts
- packages/@orbit/data/src/source-interfaces/pushable.ts
The Pullable and Pushable interfaces are now redundant with Queryable and Updatable, respectively.
Closes #829
> Deprecate Pullable and Pushable interfaces

- packages/@orbit/jsonapi/src/jsonapi-serializer.ts
- packages/@orbit/jsonapi/src/serializers/jsonapi-resource-field-serializer.ts
- packages/@orbit/jsonapi/src/serializers/jsonapi-resource-serializer.ts
- packages/@orbit/jsonapi/src/serializers/jsonapi-serializer-builder.ts
- packages/@orbit/jsonapi/test/jsonapi-serializer-test.ts
- packages/@orbit/jsonapi/test/serializers/jsonapi-atomic-operation-serializer-test.ts
- packages/@orbit/jsonapi/test/serializers/jsonapi-document-serializer-test.ts
- packages/@orbit/jsonapi/test/serializers/jsonapi-resource-field-serializer-test.ts
- packages/@orbit/jsonapi/test/serializers/jsonapi-resource-serializer-test.ts
- packages/@orbit/records/src/record-schema.ts
- packages/@orbit/serializers/src/base-serializer.ts
- packages/@orbit/serializers/src/boolean-serializer.ts
- packages/@orbit/serializers/src/date-serializer.ts
- packages/@orbit/serializers/src/date-time-serializer.ts
- packages/@orbit/serializers/src/number-serializer.ts
- packages/@orbit/serializers/src/serializer-builders.ts
- packages/@orbit/serializers/src/serializer.ts
- packages/@orbit/serializers/src/string-serializer.ts
- packages/@orbit/serializers/test/boolean-serializer-test.ts
- packages/@orbit/serializers/test/date-serializer-test.ts
- packages/@orbit/serializers/test/date-time-serializer-test.ts
- packages/@orbit/serializers/test/number-serializer-test.ts
- packages/@orbit/serializers/test/serializer-builders-test.ts
- packages/@orbit/serializers/test/string-serializer-test.ts
This PR makes a cleanup pass on a number of issues related to serialization prior to the launch of the new interfaces in v0.17.
First of all, the model definitions used to define a schema now expect `serializationOptions` and `deserializationOptions` to be shortened to simply `serialization` and `deserialization`:
```diff
const person: ModelDefinition = {
attributes: {
name: { type: 'string' },
birthday: { type: 'date' },
height: {
type: 'distance',
-      serializationOptions: { format: 'cm', digits: 2 },
-      deserializationOptions: { format: 'cm' }
+      serialization: { format: 'cm', digits: 2 },
+      deserialization: { format: 'cm' }
}
}
};
```
The old names are deprecated for now, but won't be supported in v0.18.
This change clears the way for a sibling set of options, …
> Refinement of serialization options

- packages/@orbit/data/src/source-interfaces/updatable.ts
- packages/@orbit/data/test/source-interfaces/updatable-test.ts
For data-only requests, `update` was mistakenly returning an empty array (`[]`) instead of `undefined` when called with a transform that was previously applied.
> Fix data-only response from `update` when a transform has already been applied

- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/indexeddb/test/indexeddb-source-test.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/local-storage/test/local-storage-source-test.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
As [pointed out](https://github.com/orbitjs/orbit/pull/842#issuecomment-856290051) by @SafaAlfulaij, the new `validatorFor` functions have not been automatically shared between record sources and their caches. Furthermore they were not shared between memory sources and their forks (generated via `fork()`). Therefore, validations may have inadvertently been happening at one layer but not the other. This PR resolves this by always passing `validatorFor` settings along unless an alternative was explicitly provided.
Thanks again for bringing this to my attention @SafaAlfulaij!
> Fix sharing of validatorFor function between record sources and caches, and memory sources and forks

- packages/@orbit/records/src/record-validators/record-attribute-validator.ts
- packages/@orbit/records/test/record-validators/record-attribute-validator-test.ts
Rather than raising an exception when `validatorFor(type)` returns `undefined` for an attribute's `type` as defined in the schema, a `type` validation issue is returned. This should be a gentler and more informative way to communicate that the `type` does not have a validator defined.
> Validate that validator exists for attribute type [records]

- packages/@orbit/memory/src/memory-source.ts
Fixes the signature of `MemorySource#merge` to respect the class-level generics.
> Fix typings for MemorySource#merge

- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
Instead of passing `transformOptions` within `options`, they can now be passed directly alongside other options. This makes for cleaner typings and clearer usage of options such as `fullResponse`.
> Improve MemorySource#merge typings and deprecate `transformOptions`

- packages/@orbit/core/src/task-queue.ts
- packages/@orbit/core/test/task-queue-test.ts
Fixes a bug in which these methods would have an unnecessary delay before resolving.
> Do not await TaskQueue settlement as part of `push`, `retry`, `skip`,  and `unshift`

- packages/@orbit/validators/src/object-validator.ts
- packages/@orbit/validators/src/standard-validators.ts
- packages/@orbit/validators/src/validator-builder.ts
- packages/@orbit/validators/test/object-validator-test.ts
- packages/@orbit/validators/test/standard-validator-test.ts
- packages/@orbit/validators/test/validator-builder-test.ts
Performs the tasks discussed in #857:
* Adds `validateObject` and registers it in `standardValidators` for `object` types
* Registers `validateDate` in `standardValidators` for `datetime` types (it's already registered for `date` types)
* Introduces the concept of an `unknown` validator to allow for a catch-all for validating types that don't have a registered validator (similar to the `unknown` serializer concept). This can be used as a no-op, or to log an error, or even to throw an exception.
Closes #857
> Fill in gaps in @orbit/validators

- website/docusaurus.config.js
When deploying to GitHub Pages, it is better to use an explicit "trailingSlash" site config.
Otherwise, GitHub Pages will add an extra trailing slash to your site urls only on direct-access (not when navigation) with a server redirect.
This behavior can have SEO impacts and create relative link issues.
> Explicitly set trailingSlash: false [website]

- packages/@orbit/jsonapi/src/jsonapi-source.ts
- packages/@orbit/jsonapi/test/jsonapi-source-queryable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-updatable-test.ts
Fixes an inconsistency in which `JSONAPISource` wasn't fully respecting the change introduced in #855.
Now, `query` will return an array of results when passed an array of `expressions` that contains a single expression. Likewise, `transform` will also return an array of results when passed an array of `operations` that contains a single operation.
> Ensure JSONAPISource query and update return arrays to match array requests

- website/static/CNAME
Persists CNAME file for ghpages so that we don't need to reset this file after every publish.
> Create CNAME for website

- packages/@orbit/memory/src/memory-cache.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-cache-test.ts
- packages/@orbit/memory/test/memory-source-queryable-test.ts
- packages/@orbit/memory/test/memory-source-test.ts
- packages/@orbit/memory/test/memory-source-updatable-test.ts
The primary use case of `MemorySource` forking is to create an isolated source and cache, which can be modified and then merged back into its base, with all the associated operations coalesced.
Because the forked `MemorySource` is "just" another `Source`, updates to it are still async, which allows for those updates to be logged, interacted with through other sources, etc. through async processes. Until now, there has been no way to synchronously make changes to a fork and then merge those back to the base source, because only updates at the source level have been tracked.
This PR introduces a new optional form of update tracking in the `cache` associated with a source. By default now, this capability will be enabled in forked caches. Any updates applied to the cache will be tracked and …
> Introduce new fork / merge possibilities in MemorySource and MemoryCache

- packages/@orbit/memory/src/memory-cache.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-cache-test.ts
Now that each MemoryCache tracks its `base` cache, if present, `reset` doesn't need to rely on a `base` cache argument.
Accepting a `base` cache argument still works, but has been deprecated.
> MemoryCache#reset now resets state to match its base cache, if present

- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-source-test.ts
Provide a `reset` method on `MemorySource` to reset the source's cache and transform log to its initial state, which will be either empty or a matching its `base`, if it has one.
> Introduce MemorySource#reset

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/test/indexeddb-cache-test.ts
By default `IndexedDBCache#migrateDB` will now call `createDB`, which idempotently creates object stores as needed.
Also, introduces `IndexedDBCache#createTransaction` to DRY up the implementation.
> IndexedDBCache: Provide a naive, idempotent default implementation of `migrateDB`

- packages/@orbit/jsonapi/src/lib/transform-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-updatable-test.ts
The logic to coalesce multiple consecutive `removeFromRelatedRecords` ops was missing. It follows the same pattern as the corresponding code to coalesce `addToRelatedRecords` ops.
> JSONAPISource: Allow multiple consecutive removeFromRelatedRecords ops to be coalesced

- packages/@orbit/jsonapi/src/lib/jsonapi-request-options.ts
- packages/@orbit/jsonapi/src/lib/query-requests.ts
- packages/@orbit/jsonapi/test/jsonapi-source-pullable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-queryable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-with-legacy-serializer-settings-test.ts
The `partialSet` request option provides explicit control over whether the resultset in a successful response should be interpreted as a partial set of related records. Currently, this option only applies to requests for related records.
Example usage: A request is made to a custom relationship `url` and you want the records returned to be added to the relationship, rather than to replace all existing members of that relationship.
If this property is not set, then `data` will be implicitly treated as a partial set of related records if:
- a `filter` option is present in the request
- a `page` option is present in the request
- a `prev` or `next` link is present in the response document's top-level `links` object.
> [jsonapi] Introduce `partialSet` request option

- website/docs/querying-data.md
- The header I think should be an H3, otherwise it doesn't show up in the navigation and gets lost.
- In my testing, it looks like the correct key is `records` in the relationship filter object... it's inconsistent between the two examples.
> [Docs] Update "Relationship filtering" section in querying docs

- packages/@orbit/record-cache/test/operation-processors/schema-validation-processor-test.ts
- packages/@orbit/records/src/record-exceptions.ts
- packages/@orbit/records/src/record-validators/record-operation-validator.ts
- packages/@orbit/records/src/record-validators/record-query-expression-validator.ts
- packages/@orbit/records/src/record-validators/record-relationship-validator.ts
- packages/@orbit/records/src/record-validators/related-record-validator.ts
- packages/@orbit/records/test/record-validators/record-operation-validator-test.ts
- packages/@orbit/records/test/record-validators/record-query-expression-validator-test.ts
- packages/@orbit/records/test/record-validators/record-relationship-validator-test.ts
- packages/@orbit/records/test/record-validators/related-record-validator-test.ts
- packages/@orbit/validators/src/validator.ts
- packages/@orbit/validators/test/validator-test.ts
The description for validation errors will now include all the descriptions of associated validation issues, which may in turn contain descriptions for nested validation issues.
For instance, instead of the generic description `record operation is invalid`, an expanded description such as the following will be used:
```
record operation is invalid
- relationship data is invalid
- relatedRecord has a type 'person' which is not an allowed type for this relationship
```
Closes #890
> Expand validation error descriptions

- packages/@orbit/coordinator/test/strategies/sync-strategy-test.ts
- packages/@orbit/core/src/exception.ts
- packages/@orbit/data/src/exception.ts
- packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
- packages/@orbit/jsonapi/src/lib/exceptions.ts
- packages/@orbit/jsonapi/test/jsonapi-request-processor-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-pullable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-pushable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-queryable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-updatable-test.ts
- packages/@orbit/jsonapi/test/jsonapi-source-with-legacy-serializer-settings-test.ts
- packages/@orbit/records/src/record-exceptions.ts
Performs some minor refactoring of exceptions:
* **BREAKING**:`ClientError`, `ServerError`, and `NetworkError` have been moved from `@orbit/data` to `@orbit/jsonapi`, the only package in which they are used.
* `Exception#description` has been deprecated in favor of the standard `message` property.
* Content-type checks in `JSONAPIRequestProcessor` have been refactored and streamlined.
> Exception refactoring

- website/docs/querying-data.md
Nit: misspelling in "cache," and updating the grammar a bit.
> Update grammar/spelling on live query section

- packages/@orbit/core/src/main.ts
A browser's built-in Crypto interface should provide the fastest and most secure UUID v4 implementation. Only default to the custom `uuid` function from `@orbit/utils` if `crypto.randomUUID` is not available.
Closes #902
> Use crypto.randomUUID by default for Orbit.uuid

- packages/@orbit/record-cache/src/async-record-cache.ts
- packages/@orbit/record-cache/src/record-cache.ts
- packages/@orbit/record-cache/src/sync-record-cache.ts
- packages/@orbit/record-cache/test/async-record-cache-test.ts
- packages/@orbit/record-cache/test/sync-record-cache-test.ts
- packages/@orbit/records/src/record-source.ts
- packages/@orbit/records/src/record-validators/record-validator-builder.ts
- packages/@orbit/records/src/standard-record-normalizer.ts
- packages/@orbit/records/test/record-source-test.ts
- packages/@orbit/records/test/standard-record-normalizer-test.ts
This setting mirrors `autoUpgrade` and `autoActivate` in that if it is left `undefined` it should be treated as `true`.
`RecordCache` and `RecordSource` use this to determine whether to build validators if none are provided.
`SyncRecordCache` and `AsyncRecordCache` also use this option to control whether a schema validation processor is included by default.
This will provide more fine-tuned control over whether validators are built and used by a source / cache than checking `Orbit.debug`.
Closes #903
**Note: This is considered a breaking change because `Orbit.debug` is no longer used to implicitly set `autoValidate`.**
> Introduce autoValidate setting for RecordCache and RecordSource

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
Adds the following warning in debug mode:
> IndexedDBCache will perform much better when it buffers bulk writes to IndexedDB. To enable buffered writes, configure IndexedDBSource or IndexedDBCache with `{ defaultTransformOptions: { useBuffer: true } }`. The only known transforms which are not fully handled by buffered writes are cascading (> 1 level of) dependent deletes. (To hide this warning set `Orbit.debug = false` or set the `useBuffer` default explicitly to `true` or `false`.)
Closes #798
> Encourage use of `useBuffer: true` for improved IndexedDB write performance

- packages/@orbit/indexeddb/src/indexeddb-source.ts
- packages/@orbit/indexeddb/test/indexeddb-source-test.ts
- packages/@orbit/local-storage/src/local-storage-source.ts
- packages/@orbit/local-storage/test/local-storage-source-test.ts
- packages/@orbit/memory/src/memory-cache.ts
- packages/@orbit/memory/src/memory-source.ts
- packages/@orbit/memory/test/memory-cache-test.ts
- packages/@orbit/memory/test/memory-source-test.ts
When a source is created with `autoValidate: false`, any associated forks and / or caches created from that source should also be created with the same setting.
> Ensure that validator settings are properly transferred to caches and forks

- packages/@orbit/jsonapi/src/jsonapi-request-processor.ts
- packages/@orbit/jsonapi/src/lib/exceptions.ts
- packages/@orbit/jsonapi/test/jsonapi-request-processor-test.ts
If a server response includes unrecognized content, the `fetch` should still raise a `ClientError` or `ServerError` as appropriate that contains the `response`. An invalid (i.e. unrecognized) content-type should not take precedence.
> Ensure that fetch errors always throw errors that contain `response` [jsonapi]

- website/docs/querying-data.md
This cost me a few minutes of head-scratching today.
See https://github.com/orbitjs/orbit/blob/d0fb7cd59e63a2315218e8087f330bb792d99977/packages/%40orbit/records/src/record-query-term.ts#L45-L91
> Fix incorrect uses of "relationship" instead of "relation" in filtering docs

- packages/@orbit/indexeddb/src/indexeddb-cache.ts
- packages/@orbit/indexeddb/test/indexeddb-cache-update-test.ts
Provide special handling in `getInverseRelationshipsAsync` for an empty array of identities.
> IndexedDBCache: Fix handling of empty operations array

- packages/@orbit/record-cache/src/live-query/live-query.ts
Use optional chaining to handle cases in which the global `process` is `null` (because `typeof null === 'object'`).
Fixes #933
> Improve robustness of isNode check

- packages/@orbit/record-cache/test/sync-record-cache-update-test.ts
Change test modules and structure to be identical for easier comparisons.
> Make sync-record-cache-update-test mirror async equivalents

- packages/@orbit/serializers/src/date-serializer.ts
- packages/@orbit/serializers/test/date-serializer-test.ts
The default date serializer looks like it intends to follow ISO 8601, and its test says "#serialize returns a date in YYYY-MM-DD form".
But it doesn't always emit YYYY-MM-DD form, because it doesn't insert leading zeros for single digit months and days. This results in dates that aren't strictly conformant to ISO 8601.
This change adds the necessary padding.
> Make date serializer respect ISO 8601

- packages/@orbit/coordinator/package.json
- packages/@orbit/core/package.json
- packages/@orbit/data/package.json
- packages/@orbit/identity-map/package.json
- packages/@orbit/immutable/package.json
- packages/@orbit/indexeddb-bucket/package.json
- packages/@orbit/indexeddb/package.json
- packages/@orbit/jsonapi/package.json
- packages/@orbit/local-storage-bucket/package.json
- packages/@orbit/local-storage/package.json
- packages/@orbit/memory/package.json
- packages/@orbit/record-cache/package.json
- packages/@orbit/records/package.json
- packages/@orbit/serializers/package.json
- packages/@orbit/utils/package.json
- packages/@orbit/validators/package.json
Addresses #969.
I added `"sideEffects": false` to the `package.json` of every non-private package — in other words, to all packages, except
- the root package,
- `orbit-website`,
- `@orbit/build`,
- and `@orbit/integration-tests`.
I think it's safe to say that the public packages are side-effect-free, or at least the benefit of flagging them as such outweigh the small probability that there may exist scenarios where one or several of the packages cannot be considered 100% side-effect-free. For the private packages, I don't think it's worthwhile spending time thinking about whether they are side-effect-free or not, as they never need to be tree-shaken by bundlers.
> Add "sideEffects": false
